/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_Khac;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class CaiDat extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form CaiDat
     */
    public CaiDat() {
        initComponents();
        DienDuLieu();
    }

    public void DienDuLieu() {
        SimpleDateFormat D = new SimpleDateFormat("HH:mm:ss");
        Date t = null;
        Date t2 = null;
        int moc1 = 0, moc2 = 0, phuthu1 = 0, phuthu2 = 0, moc3 = 0, moc4 = 0, phuthu3 = 0, phuthu4 = 0;

        ResultSet rs = DAO.DAO_Khac.LayBangKhac(3);
        ResultSet rs2 = DAO.DAO_Khac.LayBangKhac(4);
        ResultSet rs3 = DAO.DAO_Khac.LayBangKhac(7);
        ResultSet rs4 = DAO.DAO_Khac.LayBangKhac(8);
        ResultSet rs5 = DAO.DAO_Khac.LayBangKhac(5);
        ResultSet rs6 = DAO.DAO_Khac.LayBangKhac(6);
        ResultSet rs7 = DAO.DAO_Khac.LayBangKhac(9);
        ResultSet rs8 = DAO.DAO_Khac.LayBangKhac(10);
        try {
            if (rs.next()) {
                t = rs.getTime("GiaTriTG");
                moc1 = rs.getInt("GiaTriSo");
            }
            if (rs2.next()) {
                moc2 = rs2.getInt("GiaTriSo");
            }
            if (rs3.next()) {
                phuthu1 = rs3.getInt("GiaTriSo");

            }
            if (rs4.next()) {
                phuthu2 = rs4.getInt("GiaTriSo");
            }
            if (rs5.next()) {
                t2 = rs5.getTime("GiaTriTG");
                moc3 = rs5.getInt("GiaTriSo");
            }
            if (rs6.next()) {
                moc4 = rs6.getInt("GiaTriSo");
            }
            if (rs7.next()) {//phu thu checkout1
                phuthu3 = rs7.getInt("GiaTriSo");
            }
            if (rs8.next()) {//phu thu checkout2
                phuthu4 = rs8.getInt("GiaTriSo");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_CheckIn.setText(D.format(t));
        txt_CheckInSom.setText(String.valueOf(moc1));
        txt_PhuThu.setText(String.valueOf(phuthu2));
        txt_CheckInSom3.setText(String.valueOf(moc2));
        txt_PhuThu2.setText(String.valueOf(phuthu1));
        txt_TimeCheckOut.setText(D.format(t2));
        txt_CheckOut.setText(String.valueOf(moc4));
        txt_PhuThu3.setText(String.valueOf(phuthu4));
        txt_CheckOut2.setText(String.valueOf(moc3));
        txt_PhuPhu4.setText(String.valueOf(phuthu3));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Nen = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_Nen2 = new javax.swing.JPanel();
        lbl_TimeCheckout = new javax.swing.JLabel();
        lbl_PhanTram5 = new javax.swing.JLabel();
        lbl_PhuThuCheckOut2 = new javax.swing.JLabel();
        txt_PhuPhu4 = new javax.swing.JTextField();
        lbl_PhanTram4 = new javax.swing.JLabel();
        lbl_TimeCheckIn = new javax.swing.JLabel();
        txt_TimeCheckOut = new javax.swing.JTextField();
        lbl_PhuThuCheckIn = new javax.swing.JLabel();
        lbl_PhuThuCheckOut = new javax.swing.JLabel();
        txt_PhuThu3 = new javax.swing.JTextField();
        lbl_PhanTram3 = new javax.swing.JLabel();
        lbl_PhanTram2 = new javax.swing.JLabel();
        txt_CheckOut2 = new javax.swing.JTextField();
        txt_CheckOut = new javax.swing.JTextField();
        lbl_Tieng = new javax.swing.JLabel();
        lbl_Tieng2 = new javax.swing.JLabel();
        lbl_PhuThuCheckIn2 = new javax.swing.JLabel();
        txt_CheckIn = new javax.swing.JTextField();
        txt_CheckInSom = new javax.swing.JTextField();
        txt_PhuThu = new javax.swing.JTextField();
        txt_CheckInSom3 = new javax.swing.JTextField();
        txt_PhuThu2 = new javax.swing.JTextField();
        lbl_Tieng3 = new javax.swing.JLabel();
        lbl_Tieng4 = new javax.swing.JLabel();
        lbl_Luu = new javax.swing.JLabel();
        lbl_CaiDat = new javax.swing.JLabel();
        lbl_Nen = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(412, 620));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Nen.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Nen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_Nen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnl_NenMouseMoved(evt);
            }
        });
        pnl_Nen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl_Nen.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 480, 10));

        pnl_Nen2.setBackground(new java.awt.Color(102, 102, 255));
        pnl_Nen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_Nen2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnl_Nen2MouseMoved(evt);
            }
        });
        pnl_Nen2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_TimeCheckout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_TimeCheckout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TimeCheckout.setText("Thời gian checkout");
        pnl_Nen2.add(lbl_TimeCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        lbl_PhanTram5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhanTram5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhanTram5.setText("% giá phòng");
        lbl_PhanTram5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnl_Nen2.add(lbl_PhanTram5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 20));

        lbl_PhuThuCheckOut2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhuThuCheckOut2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhuThuCheckOut2.setText("Phụ thu checkout 2");
        lbl_PhuThuCheckOut2.setToolTipText("phụ thu khi checkin sớm trước giờ checkin mốc 1 ");
        pnl_Nen2.add(lbl_PhuThuCheckOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 30));

        txt_PhuPhu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhuPhu4ActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_PhuPhu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 140, 30));

        lbl_PhanTram4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhanTram4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhanTram4.setText("% giá phòng");
        lbl_PhanTram4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnl_Nen2.add(lbl_PhanTram4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, 20));

        lbl_TimeCheckIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_TimeCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TimeCheckIn.setText("Thời gian check in");
        pnl_Nen2.add(lbl_TimeCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));
        pnl_Nen2.add(txt_TimeCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 140, 30));

        lbl_PhuThuCheckIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhuThuCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhuThuCheckIn.setText("Phụ thu check in 1");
        lbl_PhuThuCheckIn.setToolTipText("phụ thu khi checkin sớm trước giờ checkin mốc 1 ");
        pnl_Nen2.add(lbl_PhuThuCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        lbl_PhuThuCheckOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhuThuCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhuThuCheckOut.setText("Phụ thu checkout 1");
        lbl_PhuThuCheckOut.setToolTipText("phụ thu khi checkin sớm trước giờ checkin mốc 1 ");
        pnl_Nen2.add(lbl_PhuThuCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 30));

        txt_PhuThu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhuThu3ActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_PhuThu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 140, 30));

        lbl_PhanTram3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhanTram3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhanTram3.setText("% giá phòng");
        lbl_PhanTram3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnl_Nen2.add(lbl_PhanTram3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 20));

        lbl_PhanTram2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhanTram2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhanTram2.setText("% giá phòng");
        lbl_PhanTram2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnl_Nen2.add(lbl_PhanTram2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, 20));

        txt_CheckOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckOut2ActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_CheckOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 140, 30));

        txt_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckOutActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 30));

        lbl_Tieng.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Tieng.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tieng.setText("(tiếng)");
        pnl_Nen2.add(lbl_Tieng, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        lbl_Tieng2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Tieng2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tieng2.setText("(tiếng)");
        pnl_Nen2.add(lbl_Tieng2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        lbl_PhuThuCheckIn2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_PhuThuCheckIn2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhuThuCheckIn2.setText("Phụ thu check in 2");
        lbl_PhuThuCheckIn2.setToolTipText("phụ thu khi checkin sớm trước giờ checkin mốc 1 ");
        pnl_Nen2.add(lbl_PhuThuCheckIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        txt_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckInActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        txt_CheckInSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckInSomActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_CheckInSom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, 30));
        pnl_Nen2.add(txt_PhuThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 30));

        txt_CheckInSom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckInSom3ActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_CheckInSom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, 30));

        txt_PhuThu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhuThu2ActionPerformed(evt);
            }
        });
        pnl_Nen2.add(txt_PhuThu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, 30));

        lbl_Tieng3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Tieng3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tieng3.setText("(tiếng)");
        pnl_Nen2.add(lbl_Tieng3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        lbl_Tieng4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Tieng4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tieng4.setText("(tiếng)");
        pnl_Nen2.add(lbl_Tieng4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        lbl_Luu.setBackground(new java.awt.Color(102, 102, 255));
        lbl_Luu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Luu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-new-ticket-32.png"))); // NOI18N
        lbl_Luu.setText("Lưu");
        lbl_Luu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Luu.setOpaque(true);
        lbl_Luu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_LuuMouseMoved(evt);
            }
        });
        lbl_Luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LuuMouseClicked(evt);
            }
        });
        pnl_Nen2.add(lbl_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 80, 30));

        lbl_CaiDat.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_CaiDat.setForeground(new java.awt.Color(153, 0, 0));
        lbl_CaiDat.setText("Cài đặt");
        pnl_Nen2.add(lbl_CaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 40));
        pnl_Nen2.add(lbl_Nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 650));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/closeMain.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnl_Nen2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        pnl_Nen.add(pnl_Nen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 650));

        getContentPane().add(pnl_Nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_NenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_NenMouseMoved
       
        lbl_Luu.setBackground(Color.white);
    }//GEN-LAST:event_pnl_NenMouseMoved

    private void pnl_Nen2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_Nen2MouseMoved
        
        lbl_Luu.setBackground(Color.white);
    }//GEN-LAST:event_pnl_Nen2MouseMoved

    private void lbl_LuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LuuMouseClicked
        DTO.DTO_Khac a = new DTO_Khac();
        try {

            a.setCheckIn(Time.valueOf(txt_CheckIn.getText()));
            System.out.println("thời gian checkin là :" + a.getCheckIn());
            txt_CheckInSom.getText();
            a.setMoc1(Integer.parseInt(txt_CheckInSom.getText()));
            System.out.println("mốc 1  là: " + a.getMoc1());
            txt_PhuThu.getText();
            a.setPhuthu1(Integer.parseInt(txt_PhuThu.getText()));
            System.out.println(" phụ thu 1 " + a.getPhuthu1());
            txt_CheckInSom3.getText();
            a.setMoc2(Integer.parseInt(txt_CheckInSom3.getText()));
            System.out.println(" mốc 2 là " + a.getMoc2());
            txt_PhuThu2.getText();
            a.setPhuthu2(Integer.parseInt(txt_PhuThu2.getText()));
            System.out.println(" phụ thu 2 là" + a.getPhuthu2());
            txt_TimeCheckOut.getText();
            a.setCheckOut(Time.valueOf(txt_TimeCheckOut.getText()));
            System.out.println(a.getCheckOut());
            txt_CheckOut.getText();
            a.setMoc3(Integer.parseInt(txt_CheckOut.getText()));
            System.out.println(a.getMoc3());
            txt_PhuThu3.getText();
            a.setPhuthu3(Integer.parseInt(txt_PhuThu3.getText()));
            System.out.println(a.getPhuthu3());
            txt_CheckOut2.getText();
            a.setMoc4(Integer.parseInt(txt_CheckOut2.getText()));
            System.out.println(a.getMoc4());
            txt_PhuPhu4.getText();
            a.setPhuthu4(Integer.parseInt(txt_PhuPhu4.getText()));
            System.out.println(a.getPhuthu4());
        } catch (Exception e) {
            thongbao.loi("Giá trị sai");
        }

        if (BLL.BLL_Khac.KT_Sua(a)) {
            DAO.DAO_Khac.Update(a);
            this.dispose();
        } else {
        }

    }//GEN-LAST:event_lbl_LuuMouseClicked

    private void lbl_LuuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LuuMouseMoved
        lbl_Luu.setBackground(Color.decode("#819FF7"));
    }//GEN-LAST:event_lbl_LuuMouseMoved

    private void txt_PhuThu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhuThu2ActionPerformed

    }//GEN-LAST:event_txt_PhuThu2ActionPerformed

    private void txt_CheckInSom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckInSom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckInSom3ActionPerformed

    private void txt_CheckInSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckInSomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckInSomActionPerformed

    private void txt_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckInActionPerformed

    private void txt_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckOutActionPerformed

    private void txt_CheckOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckOut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckOut2ActionPerformed

    private void txt_PhuThu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhuThu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhuThu3ActionPerformed

    private void txt_PhuPhu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhuPhu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhuPhu4ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaiDat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_CaiDat;
    private javax.swing.JLabel lbl_Luu;
    private javax.swing.JLabel lbl_Nen;
    private javax.swing.JLabel lbl_PhanTram2;
    private javax.swing.JLabel lbl_PhanTram3;
    private javax.swing.JLabel lbl_PhanTram4;
    private javax.swing.JLabel lbl_PhanTram5;
    private javax.swing.JLabel lbl_PhuThuCheckIn;
    private javax.swing.JLabel lbl_PhuThuCheckIn2;
    private javax.swing.JLabel lbl_PhuThuCheckOut;
    private javax.swing.JLabel lbl_PhuThuCheckOut2;
    private javax.swing.JLabel lbl_Tieng;
    private javax.swing.JLabel lbl_Tieng2;
    private javax.swing.JLabel lbl_Tieng3;
    private javax.swing.JLabel lbl_Tieng4;
    private javax.swing.JLabel lbl_TimeCheckIn;
    private javax.swing.JLabel lbl_TimeCheckout;
    private javax.swing.JPanel pnl_Nen;
    private javax.swing.JPanel pnl_Nen2;
    private javax.swing.JTextField txt_CheckIn;
    private javax.swing.JTextField txt_CheckInSom;
    private javax.swing.JTextField txt_CheckInSom3;
    private javax.swing.JTextField txt_CheckOut;
    private javax.swing.JTextField txt_CheckOut2;
    private javax.swing.JTextField txt_PhuPhu4;
    private javax.swing.JTextField txt_PhuThu;
    private javax.swing.JTextField txt_PhuThu2;
    private javax.swing.JTextField txt_PhuThu3;
    private javax.swing.JTextField txt_TimeCheckOut;
    // End of variables declaration//GEN-END:variables
}
