/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_ThuePhong;
//import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class frm_ThuePhong extends javax.swing.JFrame {

    Date d = new Date();
    /**
     * Creates new form frm_ThuePhong
     */
    public static frm_ThuePhong form;

    public frm_ThuePhong() {
        initComponents();
        form = this;
        rab_Gio.setSelected(true);
//        txt_NgayRa.setMinSelectableDate(d);
        txt_NgayRa.setDate(d);
        Date d = new Date();
        txt_NgayRa.setMinSelectableDate(d);
//System.out.println(java.time.LocalTime.now());
    }
    public static String MaPhong, GiaTheoGio, GiaTheoNgay;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_TenKH = new javax.swing.JLabel();
        cbb_KhachHang = new javax.swing.JComboBox<>();
        btn_ThemKH = new javax.swing.JButton();
        lbl_Phong = new javax.swing.JLabel();
        lbl2_Phong = new javax.swing.JLabel();
        lbl_NgayThue = new javax.swing.JLabel();
        txt_NgayThue = new javax.swing.JTextField();
        lbl_SoNguoi = new javax.swing.JLabel();
        txt_SoNguoi = new javax.swing.JTextField();
        lbl_GiaTheoGio = new javax.swing.JLabel();
        lbl2_GiaTheoGio = new javax.swing.JLabel();
        lbl_GiaNgay = new javax.swing.JLabel();
        lbl2_GiaNgay = new javax.swing.JLabel();
        lbl_NgayRaDuKien = new javax.swing.JLabel();
        rab_Ngay = new javax.swing.JRadioButton();
        rab_Gio = new javax.swing.JRadioButton();
        txt_NgayRa = new com.toedter.calendar.JDateChooser();
        btn_Tru = new javax.swing.JButton();
        btn_Cong = new javax.swing.JButton();
        lbl_TienCoc = new javax.swing.JLabel();
        txt_TienCoc = new javax.swing.JTextField();
        lbl_vnd = new javax.swing.JLabel();
        btn_Thue = new javax.swing.JButton();
        btn_DatTruoc = new javax.swing.JButton();
        lbl_ThuePhong = new javax.swing.JLabel();
        lbl_Nen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thuê Phòng");
        setMinimumSize(new java.awt.Dimension(580, 750));
        setPreferredSize(new java.awt.Dimension(790, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_TenKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_TenKH.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TenKH.setText("Tên khách hàng");
        getContentPane().add(lbl_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        cbb_KhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cbb_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 267, 40));

        btn_ThemKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-add-list-32.png"))); // NOI18N
        btn_ThemKH.setText("Thêm mới");
        btn_ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKHActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        lbl_Phong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Phong.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Phong.setText("Phòng");
        getContentPane().add(lbl_Phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        lbl2_Phong.setBackground(new java.awt.Color(153, 255, 153));
        lbl2_Phong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl2_Phong.setOpaque(true);
        getContentPane().add(lbl2_Phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 260, 25));

        lbl_NgayThue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_NgayThue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NgayThue.setText("Ngày thuê");
        getContentPane().add(lbl_NgayThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        txt_NgayThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_NgayThue.setFocusable(false);
        getContentPane().add(txt_NgayThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 260, 260, 30));

        lbl_SoNguoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_SoNguoi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SoNguoi.setText("Số người");
        getContentPane().add(lbl_SoNguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        txt_SoNguoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SoNguoi.setText("1");
        txt_SoNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoNguoiActionPerformed(evt);
            }
        });
        txt_SoNguoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SoNguoiKeyReleased(evt);
            }
        });
        getContentPane().add(txt_SoNguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 160, -1));

        lbl_GiaTheoGio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_GiaTheoGio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_GiaTheoGio.setText("Giá theo giờ");
        getContentPane().add(lbl_GiaTheoGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        lbl2_GiaTheoGio.setBackground(new java.awt.Color(255, 255, 255));
        lbl2_GiaTheoGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl2_GiaTheoGio.setOpaque(true);
        getContentPane().add(lbl2_GiaTheoGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 260, 30));

        lbl_GiaNgay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_GiaNgay.setForeground(new java.awt.Color(255, 255, 255));
        lbl_GiaNgay.setText("Giá ngày");
        getContentPane().add(lbl_GiaNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        lbl2_GiaNgay.setBackground(new java.awt.Color(255, 255, 255));
        lbl2_GiaNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl2_GiaNgay.setOpaque(true);
        getContentPane().add(lbl2_GiaNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 260, 30));

        lbl_NgayRaDuKien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_NgayRaDuKien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NgayRaDuKien.setText("Ngày ra dự kiến");
        getContentPane().add(lbl_NgayRaDuKien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        buttonGroup1.add(rab_Ngay);
        rab_Ngay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Ngay.setForeground(new java.awt.Color(255, 255, 255));
        rab_Ngay.setText("Thuê theo ngày");
        rab_Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rab_NgayActionPerformed(evt);
            }
        });
        getContentPane().add(rab_Ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        buttonGroup1.add(rab_Gio);
        rab_Gio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Gio.setForeground(new java.awt.Color(255, 255, 255));
        rab_Gio.setText("Thuê theo giờ");
        rab_Gio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rab_GioActionPerformed(evt);
            }
        });
        getContentPane().add(rab_Gio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        txt_NgayRa.setDateFormatString("dd-MM-yyyy HH:mm:ss");
        txt_NgayRa.setFocusable(false);
        txt_NgayRa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_NgayRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 267, 30));

        btn_Tru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Tru.setText("-");
        btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Tru, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        btn_Cong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Cong.setText("+");
        btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CongActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cong, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        lbl_TienCoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_TienCoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TienCoc.setText("Tiền cọc");
        getContentPane().add(lbl_TienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        txt_TienCoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TienCoc.setText("0");
        txt_TienCoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TienCocKeyReleased(evt);
            }
        });
        getContentPane().add(txt_TienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 420, 260, 30));

        lbl_vnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_vnd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vnd.setText("(VNĐ)");
        getContentPane().add(lbl_vnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 50, 40));

        btn_Thue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Thue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-new-ticket-32.png"))); // NOI18N
        btn_Thue.setText("Thuê");
        btn_Thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThueActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Thue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 120, 40));

        btn_DatTruoc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_DatTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-rent-32 (2).png"))); // NOI18N
        btn_DatTruoc.setText("Đặt trước");
        btn_DatTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatTruocActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DatTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, 39));

        lbl_ThuePhong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_ThuePhong.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ThuePhong.setText("THUÊ PHÒNG");
        getContentPane().add(lbl_ThuePhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 170, -1));

        lbl_Nen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/FromThueDatPhong.JPG"))); // NOI18N
        lbl_Nen.setPreferredSize(new java.awt.Dimension(789, 500));
        getContentPane().add(lbl_Nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 520));

        jPanel1.setBackground(new java.awt.Color(76, 132, 142));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Sans-White-TBG.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 790, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void loadData_KH() {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb_KhachHang.getModel();
        cbbModel.removeAllElements();
        ResultSet rs = DAO.DAO_KhachHang.LayKH();
        try {
            while (rs.next()) {
                Object MaKH = rs.getString("MaKhachHang");
                Object TenKH = rs.getString("TenKhachHang");
                mycombobox mb = new mycombobox(MaKH, TenKH);
                cbbModel.addElement(mb);
            }
        } catch (SQLException ex) {
            System.out.println("lỗi đổ cbb_KhachHang");
        }
    }
    private void btn_ThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKHActionPerformed
        FrmMain frm = FrmMain.b;
        pnl_KhachHang pnl = new pnl_KhachHang();
        try {
            frm.tab.setSelectedComponent(pnl_KhachHang.form);
        } catch (Exception e) {

            frm.tab.add("Khách hàng", pnl);
            frm.tab.setSelectedComponent(pnl);
            frm.setVisible(true);
            pnl.moform();
        }


    }//GEN-LAST:event_btn_ThemKHActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (BLL.BLL_DangNhap.quyen.equals("QuanLy")) {

        }
        loadData_KH();
        lbl2_Phong.setText(String.valueOf(MaPhong));
        lbl2_GiaTheoGio.setText(GiaTheoGio);
        lbl2_GiaNgay.setText(GiaTheoNgay);

        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        txt_NgayThue.setText(s.format(d));
    }//GEN-LAST:event_formWindowOpened

    private void btn_ThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThueActionPerformed
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        DTO.DTO_ThuePhong add = new DTO_ThuePhong();
        GUI.mycombobox mb = (GUI.mycombobox) cbb_KhachHang.getSelectedItem();
        add.setMaKH(mb.value.toString());
        add.setMaPhong(lbl2_Phong.getText());
        if (rab_Gio.isSelected()) {
            add.setLoaiHinhThue(true);

        } else {
            add.setLoaiHinhThue(false);
        }
        add.setNgayThue(txt_NgayThue.getText());
        try {
            add.setNgayRaDuKien(s.format(txt_NgayRa.getDate()));
        } catch (Exception e) {
            thongbao.loi("Ngày ra dự kiến sai");
            return;
        }
        add.setSoNguoi(txt_SoNguoi.getText());
        add.setTenUser(BLL.BLL_DangNhap.TenUser);
        add.setTienCoc(0);

        if (!txt_TienCoc.getText().trim().equals("")) {
            add.setTienCoc(ChuyenDoi.ChuyenSangSo(txt_TienCoc.getText()));
        }

        boolean kt = BLL.BLL_ThuePhong.KT_Them(add);
        if (kt) {
            DAO.DAO_ThuePhong.Them(add);

            this.dispose();
            //mở lại form thuê phòng
            FrmMain frm = FrmMain.b;
            frm.tab.remove(pnl_DSphong.form);
            pnl_DSphong pnl = new pnl_DSphong();
            frm.tab.add("Danh sách phòng", pnl);
            frm.tab.setSelectedComponent(pnl);
        }

    }//GEN-LAST:event_btn_ThueActionPerformed
    String NgayRaDuKien = "";
    private void rab_GioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rab_GioActionPerformed
        txt_NgayRa.setDateFormatString("dd-MM-yyyy HH:mm:ss");
    }//GEN-LAST:event_rab_GioActionPerformed

    private void rab_NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rab_NgayActionPerformed
        SimpleDateFormat s = new SimpleDateFormat("HH:mm:ss");

        ResultSet rs = DAO.DAO_Khac.LayBangKhac(5);
        String gio = "";
        try {
            if (rs.next()) {
                gio = s.format(rs.getTime("GiaTriTG"));
                System.out.println(gio);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm_ThuePhong.class.getName()).log(Level.SEVERE, null, ex);
        }

        Calendar c2 = Calendar.getInstance();
        c2.setTime(d);
        c2.add(Calendar.DATE, 1);
//        System.out.println(c2.getTime());
        txt_NgayRa.setDate(c2.getTime());
        txt_NgayRa.setDateFormatString("dd-MM-yyyy " + gio);

        //System.out.println("ngày ra"+c2.getTime());
    }//GEN-LAST:event_rab_NgayActionPerformed

    private void txt_SoNguoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoNguoiKeyReleased
        try {
            int sl = Integer.parseInt(txt_SoNguoi.getText());

        } catch (Exception e) {
            txt_SoNguoi.setText("01");

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoNguoiKeyReleased

    private void btn_TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TruActionPerformed
        try {
            if (Integer.parseInt(txt_SoNguoi.getText()) > 1) {
                SoNGuoi(-1);
            }
        } catch (Exception e) {
            txt_SoNguoi.setText("0");

        }
    }//GEN-LAST:event_btn_TruActionPerformed

    private void btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CongActionPerformed
        SoNGuoi(1);
    }//GEN-LAST:event_btn_CongActionPerformed

    private void txt_TienCocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TienCocKeyReleased
        try {
//            int sl = Integer.parseInt(txt_TienCoc.getText());
//            String chuoi = txtKhachTra.getText();
            double so = ChuyenDoi.ChuyenSangSo(txt_TienCoc.getText());
            String sotien = ChuyenDoi.DinhDangSo(so);
            txt_TienCoc.setText(sotien);
//txt_TienCoc.setText(ChuyenDoi.DinhDangSo(sl));
        } catch (Exception e) {
//            txt_TienCoc.setText("");

        }
    }//GEN-LAST:event_txt_TienCocKeyReleased

    private void btn_DatTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatTruocActionPerformed
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        DTO.DTO_ThuePhong add = new DTO_ThuePhong();
        GUI.mycombobox mb = (GUI.mycombobox) cbb_KhachHang.getSelectedItem();
        add.setMaKH(mb.value.toString());
        add.setMaPhong(lbl2_Phong.getText());
        if (rab_Gio.isSelected()) {
            add.setLoaiHinhThue(true);
        } else {
            add.setLoaiHinhThue(false);
        }
        add.setNgayThue(txt_NgayThue.getText());
        try {
            add.setNgayRaDuKien(s.format(txt_NgayRa.getDate()));
        } catch (Exception e) {
            thongbao.loi("Ngày ra dự kiến sai");
            return;
        }
        add.setSoNguoi(txt_SoNguoi.getText());
        add.setTenUser(BLL.BLL_DangNhap.TenUser);

        if (!txt_TienCoc.getText().trim().equals("")) {
            add.setTienCoc(ChuyenDoi.ChuyenSangSo(txt_TienCoc.getText()));
        }
        DAO.DAO_ThuePhong.DatTruocPhong(add);
        this.dispose();
        //mở lại form thuê phòng
        FrmMain frm = FrmMain.b;
        frm.tab.remove(pnl_DSphong.form);
        pnl_DSphong pnl = new pnl_DSphong();
        frm.tab.add("Danh sách phòng", pnl);
        frm.tab.setSelectedComponent(pnl);

    }//GEN-LAST:event_btn_DatTruocActionPerformed

    private void txt_SoNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoNguoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoNguoiActionPerformed
    private void SoNGuoi(int giatri) {
        int sl = Integer.parseInt(txt_SoNguoi.getText());
        sl = sl + (giatri);
        txt_SoNguoi.setText(String.valueOf(sl));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ThuePhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ThuePhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cong;
    private javax.swing.JButton btn_DatTruoc;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.JButton btn_Thue;
    private javax.swing.JButton btn_Tru;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbb_KhachHang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl2_GiaNgay;
    private javax.swing.JLabel lbl2_GiaTheoGio;
    private javax.swing.JLabel lbl2_Phong;
    private javax.swing.JLabel lbl_GiaNgay;
    private javax.swing.JLabel lbl_GiaTheoGio;
    private javax.swing.JLabel lbl_Nen;
    private javax.swing.JLabel lbl_NgayRaDuKien;
    private javax.swing.JLabel lbl_NgayThue;
    private javax.swing.JLabel lbl_Phong;
    private javax.swing.JLabel lbl_SoNguoi;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_ThuePhong;
    private javax.swing.JLabel lbl_TienCoc;
    private javax.swing.JLabel lbl_vnd;
    private javax.swing.JRadioButton rab_Gio;
    private javax.swing.JRadioButton rab_Ngay;
    private com.toedter.calendar.JDateChooser txt_NgayRa;
    private javax.swing.JTextField txt_NgayThue;
    private javax.swing.JTextField txt_SoNguoi;
    private javax.swing.JTextField txt_TienCoc;
    // End of variables declaration//GEN-END:variables
}
