/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import javax.swing.JOptionPane;
import DAO.connection;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
/**
 *
 * @author DELL
 */
public class FrmDangNhap extends javax.swing.JFrame {
int showHidePass = 1;
   public static DAO.connection conn =new connection();
    /**
     * Creates new form FrmDangNhap
     */
    public FrmDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        //this.getRootPane().setDefaultButton(btnDangnhap);
    }
     private void showHidePassword() {
        showHidePass++;
        if (showHidePass % 2 == 0) {
            Image img = getToolkit().createImage(getClass().getResource("/HinhAnh/eyeBlack.png"));
            btnEye.setIcon(new ImageIcon(img));
            txtMK.setEchoChar((char) 0);
        } else {
            Image img = getToolkit().createImage(getClass().getResource("/HinhAnh/eyeHideBlack.png"));
            btnEye.setIcon(new ImageIcon(img));
            txtMK.setEchoChar('\u25cf');
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEye = new javax.swing.JButton();
        lblquenmatkhau = new javax.swing.JLabel();
        btnDangnhap = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/logodangnhap1.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 140));

        btnEye.setBackground(new java.awt.Color(255, 255, 255));
        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/eyeHideBlack.png"))); // NOI18N
        btnEye.setBorder(null);
        btnEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEyeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 40, 30));

        lblquenmatkhau.setForeground(new java.awt.Color(255, 0, 0));
        lblquenmatkhau.setText("Quên Mật Khẩu");
        getContentPane().add(lblquenmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        btnDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-login-32 (1).png"))); // NOI18N
        btnDangnhap.setText("Đăng Nhập");
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 150, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-cancel-32.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 150, 40));

        txtusername.setText("admin");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 210, 30));

        txtMK.setText("admin");
        getContentPane().add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/formdangnhap.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
      // JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không");
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
        // TODO add your handling code here:
        String TenTK, MK;
        TenTK = txtusername.getText();
        MK = String.valueOf(txtMK.getPassword());
        boolean kt = BLL.BLL_DangNhap.KT_DangNhap(TenTK, MK);
        if (kt) {
           
           
            thongbao.thongbao("Đăng Nhập Thành Công");
             this.dispose();
             FrmMain frm = new FrmMain();
            frm.setVisible(true);
            
        } 
        
    }//GEN-LAST:event_btnDangnhapActionPerformed

    private void btnEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEyeActionPerformed
        // TODO add your handling code here:
        showHidePassword();

    }//GEN-LAST:event_btnEyeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JButton btnEye;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblquenmatkhau;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
