/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class FrmMain extends javax.swing.JFrame {

    int showhidemenu = 1;
    public static FrmMain b;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        pnlSubNhanVien.setVisible(false);
        pnlSubKhachHang.setVisible(false);
        pnlSubPhong.setVisible(false);
        pnlSubTaiKhoan.setVisible(false);
        pnlSubCaiDat.setVisible(false);
        b = this;
        showtime();
        btnTrangChuActionPerformed(null);
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat D = new SimpleDateFormat("dd/MM/yyyy");
                lbltime.setText(s.format(d) + "-" + D.format(d));
            }
        }).start();
    }

    void showHideSubMenu(int so, JPanel panel) {
        so++;
        if (so % 2 == 0) {
            pnlSubNhanVien.setVisible(true);
            pnlSubKhachHang.setVisible(true);
            pnlSubPhong.setVisible(true);
            pnlSubTaiKhoan.setVisible(true);
            pnlSubCaiDat.setVisible(true);

        } else {
            pnlSubNhanVien.setVisible(false);
            pnlSubKhachHang.setVisible(false);
            pnlSubPhong.setVisible(false);
            pnlSubTaiKhoan.setVisible(false);
            pnlSubCaiDat.setVisible(false);
        }
        JPanel[] pnl = new JPanel[]{pnlSubCaiDat, pnlSubKhachHang, pnlSubNhanVien, pnlSubPhong, pnlSubTaiKhoan};
        for (int i = 0; i < pnl.length; i++) {
            pnl[i].setVisible(false);
        }
        panel.setVisible(true);
    }

    void hover(int so, JPanel pnl) {
        if (so == 1) {
            pnl.setBackground(new Color(13, 78, 144));
            pnl.setCursor(new Cursor(HAND_CURSOR));

        } else {
            pnl.setBackground(new Color(0, 34, 68));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        pnlTrangchu = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        pnlPhong = new javax.swing.JPanel();
        btnPhong = new javax.swing.JButton();
        pnlKhachHang = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        pnlNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        pnlThongKe = new javax.swing.JPanel();
        btnThongke = new javax.swing.JButton();
        pnlTaikhoan = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        pnlCaiDat = new javax.swing.JPanel();
        btnCaiDat = new javax.swing.JButton();
        pnlSubPhong = new javax.swing.JPanel();
        pnlThuePhong = new javax.swing.JPanel();
        btnThuePhong = new javax.swing.JButton();
        pnlLoaiPhong = new javax.swing.JPanel();
        btnLoaiPhong = new javax.swing.JButton();
        pnlDsDatPhong = new javax.swing.JPanel();
        btnDsDatPhong = new javax.swing.JButton();
        pnlDsPhong = new javax.swing.JPanel();
        btnDsPhong = new javax.swing.JButton();
        pnlLoaiDichVu = new javax.swing.JPanel();
        btnLoaiDichVu = new javax.swing.JButton();
        pnlDichVuPhong = new javax.swing.JPanel();
        btnDichVuPhong = new javax.swing.JButton();
        pnlSubKhachHang = new javax.swing.JPanel();
        pnlDanhSachKhachHang = new javax.swing.JPanel();
        btnDanhSachKhachHang = new javax.swing.JButton();
        pnlLoaiKhachHang = new javax.swing.JPanel();
        btnLoaiKhachHang = new javax.swing.JButton();
        pnlSubNhanVien = new javax.swing.JPanel();
        pnlDanhSachNhanVien = new javax.swing.JPanel();
        btnDanhSachNhanVien = new javax.swing.JButton();
        pnlLuongNhanVien = new javax.swing.JPanel();
        btnLuongiNhanVien = new javax.swing.JButton();
        pnlSubTaiKhoan = new javax.swing.JPanel();
        pnlDangNhap = new javax.swing.JPanel();
        btnDangNhap = new javax.swing.JButton();
        pnlDangXuat = new javax.swing.JPanel();
        btnDangxuat = new javax.swing.JButton();
        pnlDoiMatKhau = new javax.swing.JPanel();
        btnDoiMatKhau = new javax.swing.JButton();
        pnlSubCaiDat = new javax.swing.JPanel();
        pnlCheckinCheckout = new javax.swing.JPanel();
        btnCheckinCheckout = new javax.swing.JButton();
        pnlLienHe = new javax.swing.JPanel();
        btnLienHe = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        pnlBottom = new javax.swing.JPanel();
        lbltime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(153, 153, 153));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/closeMain.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/minusMain.png"))); // NOI18N
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setDefaultCapable(false);
        btnMinus.setFocusPainted(false);
        btnMinus.setFocusable(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(1261, Short.MAX_VALUE)
                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 30));

        pnlMenu.setBackground(new java.awt.Color(0, 34, 68));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTrangchu.setBackground(new java.awt.Color(0, 34, 68));

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-home-32 (2).png"))); // NOI18N
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setContentAreaFilled(false);
        btnTrangChu.setDefaultCapable(false);
        btnTrangChu.setFocusPainted(false);
        btnTrangChu.setFocusable(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setIconTextGap(25);
        btnTrangChu.setLabel("Trang chủ");
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangchuLayout = new javax.swing.GroupLayout(pnlTrangchu);
        pnlTrangchu.setLayout(pnlTrangchuLayout);
        pnlTrangchuLayout.setHorizontalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        pnlTrangchuLayout.setVerticalGroup(
            pnlTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangchuLayout.createSequentialGroup()
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlTrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlPhong.setBackground(new java.awt.Color(0, 34, 68));

        btnPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-room-32 (1).png"))); // NOI18N
        btnPhong.setText("Quản Lý Phòng");
        btnPhong.setBorder(null);
        btnPhong.setBorderPainted(false);
        btnPhong.setContentAreaFilled(false);
        btnPhong.setDefaultCapable(false);
        btnPhong.setFocusPainted(false);
        btnPhong.setFocusable(false);
        btnPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhong.setIconTextGap(25);
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongMouseExited(evt);
            }
        });
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPhongLayout = new javax.swing.GroupLayout(pnlPhong);
        pnlPhong.setLayout(pnlPhongLayout);
        pnlPhongLayout.setHorizontalGroup(
            pnlPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlPhongLayout.setVerticalGroup(
            pnlPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhongLayout.createSequentialGroup()
                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 0, 210, -1));

        pnlKhachHang.setBackground(new java.awt.Color(0, 34, 68));
        pnlKhachHang.setPreferredSize(new java.awt.Dimension(220, 70));

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-account-32.png"))); // NOI18N
        btnKhachHang.setText("Quản Lý Khách Hàng");
        btnKhachHang.setBorder(null);
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setContentAreaFilled(false);
        btnKhachHang.setDefaultCapable(false);
        btnKhachHang.setFocusPainted(false);
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setIconTextGap(25);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhachHangLayout.createSequentialGroup()
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 210, -1));

        pnlNhanVien.setBackground(new java.awt.Color(0, 34, 68));
        pnlNhanVien.setPreferredSize(new java.awt.Dimension(220, 70));

        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-customer-insights-manager-32.png"))); // NOI18N
        btnNhanVien.setText("Quản Lý Nhân Viên");
        btnNhanVien.setBorder(null);
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setDefaultCapable(false);
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setIconTextGap(25);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 210, -1));

        pnlThongKe.setBackground(new java.awt.Color(0, 34, 68));
        pnlThongKe.setPreferredSize(new java.awt.Dimension(220, 70));

        btnThongke.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(255, 255, 255));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-statistics-32.png"))); // NOI18N
        btnThongke.setText("Thống Kê");
        btnThongke.setBorder(null);
        btnThongke.setBorderPainted(false);
        btnThongke.setContentAreaFilled(false);
        btnThongke.setDefaultCapable(false);
        btnThongke.setFocusPainted(false);
        btnThongke.setFocusable(false);
        btnThongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongke.setIconTextGap(25);
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongkeMouseExited(evt);
            }
        });
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 210, -1));

        pnlTaikhoan.setBackground(new java.awt.Color(0, 34, 68));
        pnlTaikhoan.setPreferredSize(new java.awt.Dimension(220, 70));

        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-male-user-32.png"))); // NOI18N
        btnTaiKhoan.setText("Tài Khoản");
        btnTaiKhoan.setBorder(null);
        btnTaiKhoan.setBorderPainted(false);
        btnTaiKhoan.setContentAreaFilled(false);
        btnTaiKhoan.setDefaultCapable(false);
        btnTaiKhoan.setFocusPainted(false);
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTaiKhoan.setIconTextGap(25);
        btnTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseExited(evt);
            }
        });
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaikhoanLayout = new javax.swing.GroupLayout(pnlTaikhoan);
        pnlTaikhoan.setLayout(pnlTaikhoanLayout);
        pnlTaikhoanLayout.setHorizontalGroup(
            pnlTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlTaikhoanLayout.setVerticalGroup(
            pnlTaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaikhoanLayout.createSequentialGroup()
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlTaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 210, -1));

        pnlCaiDat.setBackground(new java.awt.Color(0, 34, 68));
        pnlCaiDat.setPreferredSize(new java.awt.Dimension(220, 70));

        btnCaiDat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCaiDat.setForeground(new java.awt.Color(255, 255, 255));
        btnCaiDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-gear-32 (1).png"))); // NOI18N
        btnCaiDat.setText("Cài Đặt");
        btnCaiDat.setBorder(null);
        btnCaiDat.setBorderPainted(false);
        btnCaiDat.setContentAreaFilled(false);
        btnCaiDat.setDefaultCapable(false);
        btnCaiDat.setFocusPainted(false);
        btnCaiDat.setFocusable(false);
        btnCaiDat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCaiDat.setIconTextGap(25);
        btnCaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCaiDatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCaiDatMouseExited(evt);
            }
        });
        btnCaiDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaiDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCaiDatLayout = new javax.swing.GroupLayout(pnlCaiDat);
        pnlCaiDat.setLayout(pnlCaiDatLayout);
        pnlCaiDatLayout.setHorizontalGroup(
            pnlCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCaiDat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlCaiDatLayout.setVerticalGroup(
            pnlCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaiDatLayout.createSequentialGroup()
                .addComponent(btnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlCaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 140, -1));

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1400, 70));

        pnlSubPhong.setBackground(new java.awt.Color(153, 255, 0));
        pnlSubPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThuePhong.setBackground(new java.awt.Color(0, 34, 68));

        btnThuePhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThuePhong.setForeground(new java.awt.Color(255, 255, 255));
        btnThuePhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-rent-32 (1).png"))); // NOI18N
        btnThuePhong.setText("Thuê Phòng");
        btnThuePhong.setBorder(null);
        btnThuePhong.setBorderPainted(false);
        btnThuePhong.setContentAreaFilled(false);
        btnThuePhong.setDefaultCapable(false);
        btnThuePhong.setFocusPainted(false);
        btnThuePhong.setFocusable(false);
        btnThuePhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThuePhong.setIconTextGap(25);
        btnThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThuePhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThuePhongMouseExited(evt);
            }
        });
        btnThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuePhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThuePhongLayout = new javax.swing.GroupLayout(pnlThuePhong);
        pnlThuePhong.setLayout(pnlThuePhongLayout);
        pnlThuePhongLayout.setHorizontalGroup(
            pnlThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlThuePhongLayout.setVerticalGroup(
            pnlThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuePhongLayout.createSequentialGroup()
                .addComponent(btnThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubPhong.add(pnlThuePhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        pnlLoaiPhong.setBackground(new java.awt.Color(0, 34, 68));

        btnLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-list-32 (1).png"))); // NOI18N
        btnLoaiPhong.setText("Loại Phòng");
        btnLoaiPhong.setBorder(null);
        btnLoaiPhong.setBorderPainted(false);
        btnLoaiPhong.setContentAreaFilled(false);
        btnLoaiPhong.setDefaultCapable(false);
        btnLoaiPhong.setFocusPainted(false);
        btnLoaiPhong.setFocusable(false);
        btnLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoaiPhong.setIconTextGap(25);
        btnLoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoaiPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoaiPhongMouseExited(evt);
            }
        });
        btnLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoaiPhongLayout = new javax.swing.GroupLayout(pnlLoaiPhong);
        pnlLoaiPhong.setLayout(pnlLoaiPhongLayout);
        pnlLoaiPhongLayout.setHorizontalGroup(
            pnlLoaiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlLoaiPhongLayout.setVerticalGroup(
            pnlLoaiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSubPhong.add(pnlLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 40));

        pnlDsDatPhong.setBackground(new java.awt.Color(0, 34, 68));

        btnDsDatPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDsDatPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnDsDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-list-32.png"))); // NOI18N
        btnDsDatPhong.setText("Danh Sách Đặt Phòng");
        btnDsDatPhong.setBorder(null);
        btnDsDatPhong.setBorderPainted(false);
        btnDsDatPhong.setContentAreaFilled(false);
        btnDsDatPhong.setDefaultCapable(false);
        btnDsDatPhong.setFocusPainted(false);
        btnDsDatPhong.setFocusable(false);
        btnDsDatPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDsDatPhong.setIconTextGap(25);
        btnDsDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDsDatPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDsDatPhongMouseExited(evt);
            }
        });
        btnDsDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsDatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDsDatPhongLayout = new javax.swing.GroupLayout(pnlDsDatPhong);
        pnlDsDatPhong.setLayout(pnlDsDatPhongLayout);
        pnlDsDatPhongLayout.setHorizontalGroup(
            pnlDsDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDsDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlDsDatPhongLayout.setVerticalGroup(
            pnlDsDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDsDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSubPhong.add(pnlDsDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 40));

        pnlDsPhong.setBackground(new java.awt.Color(0, 34, 68));

        btnDsPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDsPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnDsPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-todo-list-32.png"))); // NOI18N
        btnDsPhong.setText("Danh Sách Phòng");
        btnDsPhong.setBorder(null);
        btnDsPhong.setBorderPainted(false);
        btnDsPhong.setContentAreaFilled(false);
        btnDsPhong.setDefaultCapable(false);
        btnDsPhong.setFocusPainted(false);
        btnDsPhong.setFocusable(false);
        btnDsPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDsPhong.setIconTextGap(25);
        btnDsPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDsPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDsPhongMouseExited(evt);
            }
        });
        btnDsPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDsPhongLayout = new javax.swing.GroupLayout(pnlDsPhong);
        pnlDsPhong.setLayout(pnlDsPhongLayout);
        pnlDsPhongLayout.setHorizontalGroup(
            pnlDsPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDsPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlDsPhongLayout.setVerticalGroup(
            pnlDsPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDsPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSubPhong.add(pnlDsPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        pnlLoaiDichVu.setBackground(new java.awt.Color(0, 34, 68));

        btnLoaiDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoaiDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-service-bell-32.png"))); // NOI18N
        btnLoaiDichVu.setText("Loại Dịch Vụ");
        btnLoaiDichVu.setBorder(null);
        btnLoaiDichVu.setBorderPainted(false);
        btnLoaiDichVu.setContentAreaFilled(false);
        btnLoaiDichVu.setDefaultCapable(false);
        btnLoaiDichVu.setFocusPainted(false);
        btnLoaiDichVu.setFocusable(false);
        btnLoaiDichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoaiDichVu.setIconTextGap(25);
        btnLoaiDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoaiDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoaiDichVuMouseExited(evt);
            }
        });
        btnLoaiDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoaiDichVuLayout = new javax.swing.GroupLayout(pnlLoaiDichVu);
        pnlLoaiDichVu.setLayout(pnlLoaiDichVuLayout);
        pnlLoaiDichVuLayout.setHorizontalGroup(
            pnlLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlLoaiDichVuLayout.setVerticalGroup(
            pnlLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSubPhong.add(pnlLoaiDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 40));

        pnlDichVuPhong.setBackground(new java.awt.Color(0, 34, 68));

        btnDichVuPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDichVuPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnDichVuPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-food-service-32.png"))); // NOI18N
        btnDichVuPhong.setText("Dịch Vụ Phòng");
        btnDichVuPhong.setBorder(null);
        btnDichVuPhong.setBorderPainted(false);
        btnDichVuPhong.setContentAreaFilled(false);
        btnDichVuPhong.setDefaultCapable(false);
        btnDichVuPhong.setFocusPainted(false);
        btnDichVuPhong.setFocusable(false);
        btnDichVuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDichVuPhong.setIconTextGap(25);
        btnDichVuPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDichVuPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDichVuPhongMouseExited(evt);
            }
        });
        btnDichVuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDichVuPhongLayout = new javax.swing.GroupLayout(pnlDichVuPhong);
        pnlDichVuPhong.setLayout(pnlDichVuPhongLayout);
        pnlDichVuPhongLayout.setHorizontalGroup(
            pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDichVuPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlDichVuPhongLayout.setVerticalGroup(
            pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDichVuPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSubPhong.add(pnlDichVuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 40));

        jPanel1.add(pnlSubPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 220, 240));

        pnlSubKhachHang.setBackground(new java.awt.Color(255, 0, 255));
        pnlSubKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDanhSachKhachHang.setBackground(new java.awt.Color(0, 34, 68));

        btnDanhSachKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDanhSachKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-todo-list-32.png"))); // NOI18N
        btnDanhSachKhachHang.setText("Danh Sách KH");
        btnDanhSachKhachHang.setBorder(null);
        btnDanhSachKhachHang.setBorderPainted(false);
        btnDanhSachKhachHang.setContentAreaFilled(false);
        btnDanhSachKhachHang.setDefaultCapable(false);
        btnDanhSachKhachHang.setFocusPainted(false);
        btnDanhSachKhachHang.setFocusable(false);
        btnDanhSachKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhSachKhachHang.setIconTextGap(25);
        btnDanhSachKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhSachKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhSachKhachHangMouseExited(evt);
            }
        });
        btnDanhSachKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhSachKhachHangLayout = new javax.swing.GroupLayout(pnlDanhSachKhachHang);
        pnlDanhSachKhachHang.setLayout(pnlDanhSachKhachHangLayout);
        pnlDanhSachKhachHangLayout.setHorizontalGroup(
            pnlDanhSachKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDanhSachKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDanhSachKhachHangLayout.setVerticalGroup(
            pnlDanhSachKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachKhachHangLayout.createSequentialGroup()
                .addComponent(btnDanhSachKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubKhachHang.add(pnlDanhSachKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        pnlLoaiKhachHang.setBackground(new java.awt.Color(0, 34, 68));

        btnLoaiKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoaiKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-communicate-skin-type-7-32.png"))); // NOI18N
        btnLoaiKhachHang.setText("Loại Khách Hàng");
        btnLoaiKhachHang.setBorder(null);
        btnLoaiKhachHang.setBorderPainted(false);
        btnLoaiKhachHang.setContentAreaFilled(false);
        btnLoaiKhachHang.setDefaultCapable(false);
        btnLoaiKhachHang.setFocusPainted(false);
        btnLoaiKhachHang.setFocusable(false);
        btnLoaiKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoaiKhachHang.setIconTextGap(25);
        btnLoaiKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoaiKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoaiKhachHangMouseExited(evt);
            }
        });
        btnLoaiKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoaiKhachHangLayout = new javax.swing.GroupLayout(pnlLoaiKhachHang);
        pnlLoaiKhachHang.setLayout(pnlLoaiKhachHangLayout);
        pnlLoaiKhachHangLayout.setHorizontalGroup(
            pnlLoaiKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLoaiKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlLoaiKhachHangLayout.setVerticalGroup(
            pnlLoaiKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiKhachHangLayout.createSequentialGroup()
                .addComponent(btnLoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubKhachHang.add(pnlLoaiKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 40));

        jPanel1.add(pnlSubKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 210, 80));

        pnlSubNhanVien.setBackground(new java.awt.Color(0, 204, 102));
        pnlSubNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDanhSachNhanVien.setBackground(new java.awt.Color(0, 34, 68));

        btnDanhSachNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDanhSachNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-list-32.png"))); // NOI18N
        btnDanhSachNhanVien.setText("Danh Sách Nhân Viên");
        btnDanhSachNhanVien.setBorder(null);
        btnDanhSachNhanVien.setBorderPainted(false);
        btnDanhSachNhanVien.setContentAreaFilled(false);
        btnDanhSachNhanVien.setDefaultCapable(false);
        btnDanhSachNhanVien.setFocusPainted(false);
        btnDanhSachNhanVien.setFocusable(false);
        btnDanhSachNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhSachNhanVien.setIconTextGap(25);
        btnDanhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDanhSachNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDanhSachNhanVienMouseExited(evt);
            }
        });
        btnDanhSachNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhSachNhanVienLayout = new javax.swing.GroupLayout(pnlDanhSachNhanVien);
        pnlDanhSachNhanVien.setLayout(pnlDanhSachNhanVienLayout);
        pnlDanhSachNhanVienLayout.setHorizontalGroup(
            pnlDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDanhSachNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlDanhSachNhanVienLayout.setVerticalGroup(
            pnlDanhSachNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachNhanVienLayout.createSequentialGroup()
                .addComponent(btnDanhSachNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubNhanVien.add(pnlDanhSachNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        pnlLuongNhanVien.setBackground(new java.awt.Color(0, 34, 68));

        btnLuongiNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuongiNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnLuongiNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-payroll-32 (1).png"))); // NOI18N
        btnLuongiNhanVien.setText("Lương Nhân Viên");
        btnLuongiNhanVien.setBorder(null);
        btnLuongiNhanVien.setBorderPainted(false);
        btnLuongiNhanVien.setContentAreaFilled(false);
        btnLuongiNhanVien.setDefaultCapable(false);
        btnLuongiNhanVien.setFocusPainted(false);
        btnLuongiNhanVien.setFocusable(false);
        btnLuongiNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLuongiNhanVien.setIconTextGap(25);
        btnLuongiNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLuongiNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLuongiNhanVienMouseExited(evt);
            }
        });
        btnLuongiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongiNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLuongNhanVienLayout = new javax.swing.GroupLayout(pnlLuongNhanVien);
        pnlLuongNhanVien.setLayout(pnlLuongNhanVienLayout);
        pnlLuongNhanVienLayout.setHorizontalGroup(
            pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLuongiNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlLuongNhanVienLayout.setVerticalGroup(
            pnlLuongNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLuongNhanVienLayout.createSequentialGroup()
                .addComponent(btnLuongiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubNhanVien.add(pnlLuongNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 40));

        jPanel1.add(pnlSubNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 210, 80));

        pnlSubTaiKhoan.setBackground(new java.awt.Color(0, 153, 51));
        pnlSubTaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDangNhap.setBackground(new java.awt.Color(0, 34, 68));

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-login-32 (1).png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setBorder(null);
        btnDangNhap.setBorderPainted(false);
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setDefaultCapable(false);
        btnDangNhap.setFocusPainted(false);
        btnDangNhap.setFocusable(false);
        btnDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangNhap.setIconTextGap(25);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDangNhapLayout = new javax.swing.GroupLayout(pnlDangNhap);
        pnlDangNhap.setLayout(pnlDangNhapLayout);
        pnlDangNhapLayout.setHorizontalGroup(
            pnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlDangNhapLayout.setVerticalGroup(
            pnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangNhapLayout.createSequentialGroup()
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubTaiKhoan.add(pnlDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        pnlDangXuat.setBackground(new java.awt.Color(0, 34, 68));

        btnDangxuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-logout-rounded-left-32 (1).png"))); // NOI18N
        btnDangxuat.setText("Đăng Xuất");
        btnDangxuat.setBorder(null);
        btnDangxuat.setBorderPainted(false);
        btnDangxuat.setContentAreaFilled(false);
        btnDangxuat.setDefaultCapable(false);
        btnDangxuat.setFocusPainted(false);
        btnDangxuat.setFocusable(false);
        btnDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangxuat.setIconTextGap(25);
        btnDangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseExited(evt);
            }
        });
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDangXuatLayout = new javax.swing.GroupLayout(pnlDangXuat);
        pnlDangXuat.setLayout(pnlDangXuatLayout);
        pnlDangXuatLayout.setHorizontalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlDangXuatLayout.setVerticalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addComponent(btnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubTaiKhoan.add(pnlDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 40));

        pnlDoiMatKhau.setBackground(new java.awt.Color(0, 34, 68));

        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-change-user-32.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setBorder(null);
        btnDoiMatKhau.setBorderPainted(false);
        btnDoiMatKhau.setContentAreaFilled(false);
        btnDoiMatKhau.setDefaultCapable(false);
        btnDoiMatKhau.setFocusPainted(false);
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoiMatKhau.setIconTextGap(25);
        btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseExited(evt);
            }
        });
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDoiMatKhauLayout = new javax.swing.GroupLayout(pnlDoiMatKhau);
        pnlDoiMatKhau.setLayout(pnlDoiMatKhauLayout);
        pnlDoiMatKhauLayout.setHorizontalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnlDoiMatKhauLayout.setVerticalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiMatKhauLayout.createSequentialGroup()
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlSubTaiKhoan.add(pnlDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 40));

        jPanel1.add(pnlSubTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, 210, -1));

        pnlSubCaiDat.setBackground(new java.awt.Color(255, 51, 204));
        pnlSubCaiDat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCheckinCheckout.setBackground(new java.awt.Color(0, 34, 68));

        btnCheckinCheckout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckinCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckinCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-time-machine-32 (1).png"))); // NOI18N
        btnCheckinCheckout.setText("CheckIn và \nCheckOut");
        btnCheckinCheckout.setBorder(null);
        btnCheckinCheckout.setBorderPainted(false);
        btnCheckinCheckout.setContentAreaFilled(false);
        btnCheckinCheckout.setDefaultCapable(false);
        btnCheckinCheckout.setFocusPainted(false);
        btnCheckinCheckout.setFocusable(false);
        btnCheckinCheckout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCheckinCheckout.setIconTextGap(25);
        btnCheckinCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckinCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckinCheckoutMouseExited(evt);
            }
        });
        btnCheckinCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCheckinCheckoutLayout = new javax.swing.GroupLayout(pnlCheckinCheckout);
        pnlCheckinCheckout.setLayout(pnlCheckinCheckoutLayout);
        pnlCheckinCheckoutLayout.setHorizontalGroup(
            pnlCheckinCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckinCheckoutLayout.createSequentialGroup()
                .addComponent(btnCheckinCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCheckinCheckoutLayout.setVerticalGroup(
            pnlCheckinCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckinCheckoutLayout.createSequentialGroup()
                .addComponent(btnCheckinCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSubCaiDat.add(pnlCheckinCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        pnlLienHe.setBackground(new java.awt.Color(0, 34, 68));

        btnLienHe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLienHe.setForeground(new java.awt.Color(255, 255, 255));
        btnLienHe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-facebook-32 (1).png"))); // NOI18N
        btnLienHe.setText("Liên Hệ");
        btnLienHe.setBorder(null);
        btnLienHe.setBorderPainted(false);
        btnLienHe.setContentAreaFilled(false);
        btnLienHe.setDefaultCapable(false);
        btnLienHe.setFocusPainted(false);
        btnLienHe.setFocusable(false);
        btnLienHe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLienHe.setIconTextGap(25);
        btnLienHe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLienHeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLienHeMouseExited(evt);
            }
        });
        btnLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLienHeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLienHeLayout = new javax.swing.GroupLayout(pnlLienHe);
        pnlLienHe.setLayout(pnlLienHeLayout);
        pnlLienHeLayout.setHorizontalGroup(
            pnlLienHeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLienHeLayout.createSequentialGroup()
                .addComponent(btnLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        pnlLienHeLayout.setVerticalGroup(
            pnlLienHeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLienHe, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubCaiDat.add(pnlLienHe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 50));

        jPanel1.add(pnlSubCaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 100, 140, 100));

        tab.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1380, 610));

        pnlBottom.setBackground(new java.awt.Color(153, 153, 153));
        pnlBottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltime.setBackground(new java.awt.Color(153, 153, 153));
        lbltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltime.setForeground(new java.awt.Color(153, 0, 0));
        lbltime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlBottom.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 310, 30));

        jPanel1.add(pnlBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1400, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuePhongActionPerformed
        // TODO add your handling code here:
        try {

            tab.setSelectedComponent(pnl_DSphong.form);
        } catch (Exception e) {
            tab.remove(pnl_DSphong.form);
           // FrmMain fm = new FrmMain();
           // fm.removeAll();///sua them sau
           //tab.removeAll();
            pnl_DSphong pnl = new pnl_DSphong();
            tab.add("Danh sách phòng", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnThuePhongActionPerformed

    private void btnLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiPhongActionPerformed
        // TODO add your handling code here:
        FrmQLphongNew frm = new FrmQLphongNew();
        frm.setVisible(true);
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnLoaiPhongActionPerformed

    private void btnDsDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsDatPhongActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_DSThuePhong.form);
        } catch (Exception e) {
           // tab.remove(pnl_DSThuePhong.form);
            tab.removeAll();
            pnl_DSThuePhong pnl = new pnl_DSThuePhong();
            tab.add("Danh sách thuê phòng", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnDsDatPhongActionPerformed

    private void btnDsPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsPhongActionPerformed
        // TODO add your handling code here:
        // frm_QLPhong frm = new frm_QLPhong();
        FrmQLphongNew frm = new FrmQLphongNew();
        frm.setVisible(true);
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnDsPhongActionPerformed

    private void btnLoaiDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiDichVuActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_CungCapDichVu.form);
        } catch (Exception e) {
            tab.removeAll();
            // tab.remove(pnl_CungCapDichVu.form);
            pnl_CungCapDichVu pnl = new pnl_CungCapDichVu();
            tab.add("Cung cấp dịch vụ", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnLoaiDichVuActionPerformed

    private void btnDichVuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuPhongActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_DichVuPhong.form);
        } catch (Exception e) {
           // tab.remove(pnl_CungCapDichVu.form);
            tab.removeAll();
            pnl_DichVuPhong pnl = new pnl_DichVuPhong();
            tab.add("Dịch vụ của phòng", pnl);
            tab.setSelectedComponent(pnl);

        }
        pnlSubPhong.setVisible(false);
    }//GEN-LAST:event_btnDichVuPhongActionPerformed

    private void btnDanhSachKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachKhachHangActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_KhachHang.form);
        } catch (Exception e) {
           // tab.remove(pnl_KhachHang.form);
            tab.removeAll();
            pnl_KhachHang pnl = new pnl_KhachHang();
            tab.add("Khách hàng", pnl);
            tab.setSelectedComponent(pnl);

        }
        pnlSubKhachHang.setVisible(false);
    }//GEN-LAST:event_btnDanhSachKhachHangActionPerformed

    private void btnLoaiKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiKhachHangActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_KhachHang.form);
        } catch (Exception e) {

            pnl_KhachHang pnl = new pnl_KhachHang();
            tab.add("Khách hàng", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubKhachHang.setVisible(false);
    }//GEN-LAST:event_btnLoaiKhachHangActionPerformed

    private void btnDanhSachNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachNhanVienActionPerformed
        // TODO add your handling code here:
        pnlSubNhanVien.setVisible(false);
        try {
            tab.setSelectedComponent(pnl_NhanVienNew.form);
        } catch (Exception e) {
          //  tab.remove(pnl_NhanVienNew.form);
            pnl_NhanVienNew pnl = new pnl_NhanVienNew();
            tab.removeAll();

            tab.add("", pnl);
            tab.setSelectedComponent(pnl);
        }
    }//GEN-LAST:event_btnDanhSachNhanVienActionPerformed

    private void btnLuongiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongiNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_LoaiLuong.form);
        } catch (Exception e) {
          //  tab.remove(pnl_LoaiLuong.form);
            pnl_LoaiLuong pnl = new pnl_LoaiLuong();
            tab.removeAll();
            tab.add("Lương", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubNhanVien.setVisible(false);
    }//GEN-LAST:event_btnLuongiNhanVienActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if (BLL.BLL_DangNhap.quyen != null) {
            JOptionPane.showMessageDialog(this, "Tài Khoản Vẫn Đang Hoạt Động", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
        pnlSubTaiKhoan.setVisible(false);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:

        FrmDangNhap dn = new FrmDangNhap();
        dn.setVisible(true);
        b.setVisible(false);
        pnlSubTaiKhoan.setVisible(false);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        FrmDoiMK frm = new FrmDoiMK();
        frm.setVisible(true);
        b.setVisible(false);
        pnlSubTaiKhoan.setVisible(false);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnCheckinCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinCheckoutActionPerformed
        // TODO add your handling code here:
        CaiDat frm = new CaiDat();
        frm.setVisible(true);
        pnlSubCaiDat.setVisible(false);
    }//GEN-LAST:event_btnCheckinCheckoutActionPerformed

    private void btnLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLienHeActionPerformed
        // TODO add your handling code here:
        pnlSubCaiDat.setVisible(false);
        try {
            Desktop.getDesktop().browse(new File("D:\\DU AN NETBEANS\\DU_AN1 (1)\\duan1_QLKhachSan\\bounty\\bounty\\Vu Lan _ Facebook.html").toURI());
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnLienHeActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        // TODO add your handling code here:
        showHideSubMenu(1, pnlSubPhong);
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlPhong);
    }//GEN-LAST:event_btnPhongMouseEntered

    private void btnPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlPhong);
    }//GEN-LAST:event_btnPhongMouseExited

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        showHideSubMenu(1, pnlSubKhachHang);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        showHideSubMenu(1, pnlSubNhanVien);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        showHideSubMenu(1, pnlSubTaiKhoan);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnCaiDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaiDatActionPerformed
        // TODO add your handling code here:
        showHideSubMenu(1, pnlSubCaiDat);
    }//GEN-LAST:event_btnCaiDatActionPerformed

    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered
        // TODO add your handling code here:
        hover(1, pnlTrangchu);
    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited
        // TODO add your handling code here:
        hover(2, pnlTrangchu);
    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        // TODO add your handling code here:
        hover(1, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        // TODO add your handling code here:
        hover(2, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        hover(1, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        hover(2, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseEntered
        // TODO add your handling code here:
        hover(1, pnlThongKe);
    }//GEN-LAST:event_btnThongkeMouseEntered

    private void btnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseExited
        // TODO add your handling code here:
        hover(2, pnlThongKe);
    }//GEN-LAST:event_btnThongkeMouseExited

    private void btnTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseEntered
        // TODO add your handling code here:
        hover(1, pnlTaikhoan);
    }//GEN-LAST:event_btnTaiKhoanMouseEntered

    private void btnTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseExited
        // TODO add your handling code here:
        hover(2, pnlTaikhoan);
    }//GEN-LAST:event_btnTaiKhoanMouseExited

    private void btnCaiDatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaiDatMouseEntered
        // TODO add your handling code here:
        hover(1, pnlCaiDat);
    }//GEN-LAST:event_btnCaiDatMouseEntered

    private void btnCaiDatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaiDatMouseExited
        // TODO add your handling code here:
        hover(2, pnlCaiDat);
    }//GEN-LAST:event_btnCaiDatMouseExited

    private void btnThuePhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThuePhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlThuePhong);
    }//GEN-LAST:event_btnThuePhongMouseEntered

    private void btnThuePhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThuePhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlThuePhong);
    }//GEN-LAST:event_btnThuePhongMouseExited

    private void btnLoaiPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiPhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlLoaiPhong);
    }//GEN-LAST:event_btnLoaiPhongMouseEntered

    private void btnLoaiPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiPhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlLoaiPhong);
    }//GEN-LAST:event_btnLoaiPhongMouseExited

    private void btnDsDatPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsDatPhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDsDatPhong);
    }//GEN-LAST:event_btnDsDatPhongMouseEntered

    private void btnDsDatPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsDatPhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlDsDatPhong);
    }//GEN-LAST:event_btnDsDatPhongMouseExited

    private void btnDsPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsPhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDsPhong);
    }//GEN-LAST:event_btnDsPhongMouseEntered

    private void btnDsPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsPhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlDsPhong);
    }//GEN-LAST:event_btnDsPhongMouseExited

    private void btnLoaiDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiDichVuMouseEntered
        // TODO add your handling code here:
        hover(1, pnlLoaiDichVu);
    }//GEN-LAST:event_btnLoaiDichVuMouseEntered

    private void btnLoaiDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiDichVuMouseExited
        // TODO add your handling code here:
        hover(2, pnlLoaiDichVu);
    }//GEN-LAST:event_btnLoaiDichVuMouseExited

    private void btnDichVuPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuPhongMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDichVuPhong);
    }//GEN-LAST:event_btnDichVuPhongMouseEntered

    private void btnDichVuPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuPhongMouseExited
        // TODO add your handling code here:
        hover(2, pnlDichVuPhong);
    }//GEN-LAST:event_btnDichVuPhongMouseExited

    private void btnPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseClicked
        // TODO add your handling code here:
        pnlPhong.setBackground(new Color(13, 78, 144));
    }//GEN-LAST:event_btnPhongMouseClicked

    private void btnDanhSachKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachKhachHangMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDanhSachKhachHang);
    }//GEN-LAST:event_btnDanhSachKhachHangMouseEntered

    private void btnDanhSachKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachKhachHangMouseExited
        // TODO add your handling code here:
        hover(2, pnlDanhSachKhachHang);
    }//GEN-LAST:event_btnDanhSachKhachHangMouseExited

    private void btnLoaiKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiKhachHangMouseEntered
        // TODO add your handling code here:
        hover(1, pnlLoaiKhachHang);
    }//GEN-LAST:event_btnLoaiKhachHangMouseEntered

    private void btnLoaiKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiKhachHangMouseExited
        // TODO add your handling code here:
        hover(2, pnlLoaiKhachHang);
    }//GEN-LAST:event_btnLoaiKhachHangMouseExited

    private void btnDanhSachNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachNhanVienMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDanhSachNhanVien);
    }//GEN-LAST:event_btnDanhSachNhanVienMouseEntered

    private void btnDanhSachNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhSachNhanVienMouseExited
        // TODO add your handling code here:
        hover(2, pnlDanhSachNhanVien);
    }//GEN-LAST:event_btnDanhSachNhanVienMouseExited

    private void btnLuongiNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuongiNhanVienMouseEntered
        // TODO add your handling code here:
        hover(1, pnlLuongNhanVien);
    }//GEN-LAST:event_btnLuongiNhanVienMouseEntered

    private void btnLuongiNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuongiNhanVienMouseExited
        // TODO add your handling code here:
        hover(2, pnlLuongNhanVien);
    }//GEN-LAST:event_btnLuongiNhanVienMouseExited

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDangNhap);
    }//GEN-LAST:event_btnDangNhapMouseEntered

    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        // TODO add your handling code here:
        hover(2, pnlDangNhap);
    }//GEN-LAST:event_btnDangNhapMouseExited

    private void btnDangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDangXuat);
    }//GEN-LAST:event_btnDangxuatMouseEntered

    private void btnDangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseExited
        // TODO add your handling code here:
        hover(2, pnlDangXuat);
    }//GEN-LAST:event_btnDangxuatMouseExited

    private void btnDoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseEntered
        // TODO add your handling code here:
        hover(1, pnlDoiMatKhau);
    }//GEN-LAST:event_btnDoiMatKhauMouseEntered

    private void btnDoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseExited
        // TODO add your handling code here:
        hover(2, pnlDoiMatKhau);
    }//GEN-LAST:event_btnDoiMatKhauMouseExited

    private void btnCheckinCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckinCheckoutMouseEntered
        // TODO add your handling code here:
        hover(1, pnlCheckinCheckout);
    }//GEN-LAST:event_btnCheckinCheckoutMouseEntered

    private void btnCheckinCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckinCheckoutMouseExited
        // TODO add your handling code here:
        hover(2, pnlCheckinCheckout);
    }//GEN-LAST:event_btnCheckinCheckoutMouseExited

    private void btnLienHeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLienHeMouseEntered
        // TODO add your handling code here:
        hover(1, pnlLienHe);
    }//GEN-LAST:event_btnLienHeMouseEntered

    private void btnLienHeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLienHeMouseExited
        // TODO add your handling code here:
        hover(2, pnlLienHe);
    }//GEN-LAST:event_btnLienHeMouseExited

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_ThongKe.form);
        } catch (Exception e) {
            tab.removeAll();
            pnl_ThongKe pnl = new pnl_ThongKe();
            tab.add("Thống kê doanh thu", pnl);
            tab.setSelectedComponent(pnl);
        }
        pnlSubNhanVien.setVisible(false);
        pnlSubKhachHang.setVisible(false);
        pnlSubPhong.setVisible(false);
        pnlSubTaiKhoan.setVisible(false);
        pnlSubCaiDat.setVisible(false);
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        this.setState(1);
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        tab.removeAll();
        pnl_trangchu pnl = new pnl_trangchu();
        tab.add("", pnl);
        pnlSubNhanVien.setVisible(false);
        pnlSubKhachHang.setVisible(false);
        pnlSubPhong.setVisible(false);
        pnlSubTaiKhoan.setVisible(false);
        pnlSubCaiDat.setVisible(false);
        //tab.setSelectedComponent(pnl);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // btnTrangChuActionPerformed(null);
        if (BLL.BLL_DangNhap.quyen.equals("NhanVien")) {
            btnNhanVien.setEnabled(false);
            btnThongke.setEnabled(false);
        } else if (BLL.BLL_DangNhap.quyen.equals("")) {
            btnCaiDat.setEnabled(false);
            btnPhong.setEnabled(false);
            btnNhanVien.setEnabled(false);
            btnKhachHang.setEnabled(false);
            btnTaiKhoan.setEnabled(false);
            btnThongke.setEnabled(false);
        } else {
            btnCaiDat.setEnabled(true);
            btnPhong.setEnabled(true);
            btnNhanVien.setEnabled(true);
            btnKhachHang.setEnabled(true);
            btnTaiKhoan.setEnabled(true);
            btnThongke.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaiDat;
    private javax.swing.JButton btnCheckinCheckout;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnDanhSachKhachHang;
    private javax.swing.JButton btnDanhSachNhanVien;
    private javax.swing.JButton btnDichVuPhong;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnDsDatPhong;
    private javax.swing.JButton btnDsPhong;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLienHe;
    private javax.swing.JButton btnLoaiDichVu;
    private javax.swing.JButton btnLoaiKhachHang;
    private javax.swing.JButton btnLoaiPhong;
    private javax.swing.JButton btnLuongiNhanVien;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnThuePhong;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCaiDat;
    private javax.swing.JPanel pnlCheckinCheckout;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlDanhSachKhachHang;
    private javax.swing.JPanel pnlDanhSachNhanVien;
    private javax.swing.JPanel pnlDichVuPhong;
    private javax.swing.JPanel pnlDoiMatKhau;
    private javax.swing.JPanel pnlDsDatPhong;
    private javax.swing.JPanel pnlDsPhong;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlLienHe;
    private javax.swing.JPanel pnlLoaiDichVu;
    private javax.swing.JPanel pnlLoaiKhachHang;
    private javax.swing.JPanel pnlLoaiPhong;
    private javax.swing.JPanel pnlLuongNhanVien;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlPhong;
    private javax.swing.JPanel pnlSubCaiDat;
    private javax.swing.JPanel pnlSubKhachHang;
    private javax.swing.JPanel pnlSubNhanVien;
    private javax.swing.JPanel pnlSubPhong;
    private javax.swing.JPanel pnlSubTaiKhoan;
    private javax.swing.JPanel pnlTaikhoan;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlThuePhong;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTrangchu;
    public javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables

}
