/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_KH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class pnl_KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form pnl_KhachHang
     */
    public static pnl_KhachHang form;
    public static int moform;
    
    public pnl_KhachHang() {
        initComponents();
        
        btn_Chon.setVisible(false);
        //moform();
        BLL.BLL_KH.dodulieu(tbl_KH);
        
        loadData_LoaiKH();
        form = this;
        btn_Chon.setEnabled(false);
        pnl3.setVisible(false);
        btn_CapNhat.setEnabled(false);
        btn_Xoa.setEnabled(false);
        btn_CapnhatLoai.setEnabled(false);
        btn_XoaLoaiKH.setEnabled(false);
        
    }
    
    private void loadData_LoaiKH() {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb_LoaiKH.getModel();
        cbbModel.removeAllElements();
        ResultSet rs = DAO.DAO_LoaiKH.LayLoaiKH();
        try {
            while (rs.next()) {
                Object MaLoaiKH = rs.getString("MaLoaiKH");
                Object TenLoaiKH = rs.getString("TenLoaiKH");
                mycombobox mb = new mycombobox(MaLoaiKH, TenLoaiKH);
                cbbModel.addElement(mb);
            }
        } catch (SQLException ex) {
            System.out.println("lỗi đổ cbb_LoaiKhachHang");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        lbl_MaKH = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        lbl_LoaiKH = new javax.swing.JLabel();
        cbb_LoaiKH = new javax.swing.JComboBox<>();
        lbl_TenKH = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lbl_Tuoi = new javax.swing.JLabel();
        txt_Tuoi = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        rab_Nam = new javax.swing.JRadioButton();
        rab_Nu = new javax.swing.JRadioButton();
        lbl_SDT = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        lbl_CMND = new javax.swing.JLabel();
        txt_CMND = new javax.swing.JTextField();
        btn_Tru = new javax.swing.JButton();
        btn_Cong = new javax.swing.JButton();
        btn_ThemLoai = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btn_Xoa = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_MoiKH = new javax.swing.JButton();
        btn_ThemKH = new javax.swing.JButton();
        pnl_TimKiem = new javax.swing.JPanel();
        lbl_TimKiem = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KH = new javax.swing.JTable();
        btn_Chon = new javax.swing.JButton();
        pnl3 = new javax.swing.JPanel();
        lbl_LoaiKH2 = new javax.swing.JLabel();
        lbl_MaLoai = new javax.swing.JLabel();
        lbl_TenLoai = new javax.swing.JLabel();
        lbl_TienGiam = new javax.swing.JLabel();
        lbl_MoTa = new javax.swing.JLabel();
        txt_MaLoai = new javax.swing.JTextField();
        txt_TenLoaiKH = new javax.swing.JTextField();
        txt_TiemGiam = new javax.swing.JTextField();
        lbl_PhanTram = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_MoTa = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_LoaiKH = new javax.swing.JTable();
        btn_ThemLoaiKH = new javax.swing.JButton();
        btn_CapnhatLoai = new javax.swing.JButton();
        btn_XoaLoaiKH = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(1380, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl.setBackground(new java.awt.Color(153, 153, 255));
        pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaKH.setText("Mã khách hàng");
        pnl2.add(lbl_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        txt_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaKH.setText("KH");
        txt_MaKH.setBorder(null);
        pnl2.add(txt_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 30));

        lbl_LoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiKH.setText("Loại khách hàng");
        pnl2.add(lbl_LoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        cbb_LoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl2.add(cbb_LoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 40));

        lbl_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenKH.setText("Tên khách hàng");
        pnl2.add(lbl_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txt_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenKH.setBorder(null);
        pnl2.add(txt_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        lbl_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tuoi.setText("Tuổi");
        pnl2.add(lbl_Tuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txt_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Tuoi.setText("01");
        txt_Tuoi.setBorder(null);
        txt_Tuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TuoiKeyReleased(evt);
            }
        });
        pnl2.add(txt_Tuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 30));

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh.setText("Giới tính");
        pnl2.add(lbl_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        buttonGroup1.add(rab_Nam);
        rab_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Nam.setText("Nam");
        pnl2.add(rab_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        buttonGroup1.add(rab_Nu);
        rab_Nu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Nu.setText("Nữ");
        pnl2.add(rab_Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        lbl_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT.setText("Số điện thoại");
        pnl2.add(lbl_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SDT.setBorder(null);
        pnl2.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, 30));

        lbl_CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CMND.setText("Số CMND");
        pnl2.add(lbl_CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txt_CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_CMND.setBorder(null);
        pnl2.add(txt_CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 170, 30));

        btn_Tru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Tru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-down-32.png"))); // NOI18N
        btn_Tru.setBorder(null);
        btn_Tru.setBorderPainted(false);
        btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TruActionPerformed(evt);
            }
        });
        pnl2.add(btn_Tru, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 40, 40));

        btn_Cong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Cong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icons8-up-32.png"))); // NOI18N
        btn_Cong.setBorder(null);
        btn_Cong.setBorderPainted(false);
        btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CongActionPerformed(evt);
            }
        });
        pnl2.add(btn_Cong, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 40, 40));

        btn_ThemLoai.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThemLoai.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnthem.png"))); // NOI18N
        btn_ThemLoai.setBorder(null);
        btn_ThemLoai.setBorderPainted(false);
        btn_ThemLoai.setContentAreaFilled(false);
        btn_ThemLoai.setDefaultCapable(false);
        btn_ThemLoai.setFocusPainted(false);
        btn_ThemLoai.setFocusable(false);
        btn_ThemLoai.setIconTextGap(0);
        btn_ThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLoaiActionPerformed(evt);
            }
        });
        pnl2.add(btn_ThemLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnl2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        pnl2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        pnl2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pnl2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        pnl2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 170, 10));

        pnl.add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -6, 550, 400));

        btn_Xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnxoa.png"))); // NOI18N
        btn_Xoa.setBorder(null);
        btn_Xoa.setBorderPainted(false);
        btn_Xoa.setContentAreaFilled(false);
        btn_Xoa.setDefaultCapable(false);
        btn_Xoa.setFocusPainted(false);
        btn_Xoa.setFocusable(false);
        btn_Xoa.setIconTextGap(0);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        pnl.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 110, 40));

        btn_CapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btncapnhat.png"))); // NOI18N
        btn_CapNhat.setBorder(null);
        btn_CapNhat.setBorderPainted(false);
        btn_CapNhat.setContentAreaFilled(false);
        btn_CapNhat.setDefaultCapable(false);
        btn_CapNhat.setFocusPainted(false);
        btn_CapNhat.setFocusable(false);
        btn_CapNhat.setIconTextGap(0);
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        pnl.add(btn_CapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 110, 40));

        btn_MoiKH.setBackground(new java.awt.Color(255, 255, 255));
        btn_MoiKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_MoiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnmoi.png"))); // NOI18N
        btn_MoiKH.setBorder(null);
        btn_MoiKH.setBorderPainted(false);
        btn_MoiKH.setContentAreaFilled(false);
        btn_MoiKH.setDefaultCapable(false);
        btn_MoiKH.setFocusPainted(false);
        btn_MoiKH.setFocusable(false);
        btn_MoiKH.setIconTextGap(0);
        btn_MoiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiKHActionPerformed(evt);
            }
        });
        pnl.add(btn_MoiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 110, 40));

        btn_ThemKH.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThemKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnthem.png"))); // NOI18N
        btn_ThemKH.setBorder(null);
        btn_ThemKH.setBorderPainted(false);
        btn_ThemKH.setContentAreaFilled(false);
        btn_ThemKH.setDefaultCapable(false);
        btn_ThemKH.setFocusPainted(false);
        btn_ThemKH.setFocusable(false);
        btn_ThemKH.setIconTextGap(0);
        btn_ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKHbtn_ThemActionPerformed(evt);
            }
        });
        pnl.add(btn_ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 110, 40));

        add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 0, 540, 671));

        pnl_TimKiem.setBackground(new java.awt.Color(153, 153, 255));

        lbl_TimKiem.setBackground(new java.awt.Color(153, 153, 255));
        lbl_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TimKiem.setText("Tìm kiếm");
        lbl_TimKiem.setOpaque(true);

        txt_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKiemKeyReleased(evt);
            }
        });

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH"
            }
        ));
        tbl_KH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_KH.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_KH.setSelectionBackground(new java.awt.Color(255, 204, 102));
        tbl_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KH);

        btn_Chon.setBackground(new java.awt.Color(153, 255, 153));
        btn_Chon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Chon.setText("Chọn");
        btn_Chon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TimKiemLayout = new javax.swing.GroupLayout(pnl_TimKiem);
        pnl_TimKiem.setLayout(pnl_TimKiemLayout);
        pnl_TimKiemLayout.setHorizontalGroup(
            pnl_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TimKiemLayout.createSequentialGroup()
                .addGroup(pnl_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Chon, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txt_TimKiem)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnl_TimKiemLayout.setVerticalGroup(
            pnl_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TimKiemLayout.createSequentialGroup()
                .addComponent(lbl_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Chon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnl_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        pnl3.setBackground(new java.awt.Color(255, 255, 255));
        pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_LoaiKH2.setBackground(new java.awt.Color(153, 153, 255));
        lbl_LoaiKH2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_LoaiKH2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LoaiKH2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoaiKH2.setText("Loại khách hàng");
        lbl_LoaiKH2.setToolTipText("");
        lbl_LoaiKH2.setOpaque(true);
        pnl3.add(lbl_LoaiKH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 42));

        lbl_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaLoai.setText("Mã loại KH");
        pnl3.add(lbl_MaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lbl_TenLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenLoai.setText("Tên loại KH");
        pnl3.add(lbl_TenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        lbl_TienGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TienGiam.setText("Tiền giảm");
        pnl3.add(lbl_TienGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        lbl_MoTa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MoTa.setText("Mô tả");
        pnl3.add(lbl_MoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        txt_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaLoai.setBorder(null);
        pnl3.add(txt_MaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 300, 30));

        txt_TenLoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenLoaiKH.setBorder(null);
        pnl3.add(txt_TenLoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 300, 30));

        txt_TiemGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TiemGiam.setText("0");
        txt_TiemGiam.setBorder(null);
        txt_TiemGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TiemGiamActionPerformed(evt);
            }
        });
        txt_TiemGiam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TiemGiamKeyReleased(evt);
            }
        });
        pnl3.add(txt_TiemGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 300, 30));

        lbl_PhanTram.setText("%");
        pnl3.add(lbl_PhanTram, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        txt_MoTa.setColumns(20);
        txt_MoTa.setRows(5);
        jScrollPane2.setViewportView(txt_MoTa);

        pnl3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 440, 70));

        tbl_LoaiKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaLoaiKH", "TenLoaiKH", "TienGiam"
            }
        ));
        tbl_LoaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiKHMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_LoaiKH);

        pnl3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 230));

        btn_ThemLoaiKH.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThemLoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemLoaiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnthem.png"))); // NOI18N
        btn_ThemLoaiKH.setBorder(null);
        btn_ThemLoaiKH.setBorderPainted(false);
        btn_ThemLoaiKH.setContentAreaFilled(false);
        btn_ThemLoaiKH.setDefaultCapable(false);
        btn_ThemLoaiKH.setFocusPainted(false);
        btn_ThemLoaiKH.setFocusable(false);
        btn_ThemLoaiKH.setIconTextGap(0);
        btn_ThemLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLoaiKHActionPerformed(evt);
            }
        });
        pnl3.add(btn_ThemLoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 110, 40));

        btn_CapnhatLoai.setBackground(new java.awt.Color(255, 255, 255));
        btn_CapnhatLoai.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapnhatLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btncapnhat.png"))); // NOI18N
        btn_CapnhatLoai.setBorder(null);
        btn_CapnhatLoai.setBorderPainted(false);
        btn_CapnhatLoai.setContentAreaFilled(false);
        btn_CapnhatLoai.setDefaultCapable(false);
        btn_CapnhatLoai.setFocusPainted(false);
        btn_CapnhatLoai.setFocusable(false);
        btn_CapnhatLoai.setIconTextGap(0);
        btn_CapnhatLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLoaiActionPerformed(evt);
            }
        });
        pnl3.add(btn_CapnhatLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 110, 40));

        btn_XoaLoaiKH.setBackground(new java.awt.Color(255, 255, 255));
        btn_XoaLoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_XoaLoaiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnxoa.png"))); // NOI18N
        btn_XoaLoaiKH.setBorder(null);
        btn_XoaLoaiKH.setBorderPainted(false);
        btn_XoaLoaiKH.setContentAreaFilled(false);
        btn_XoaLoaiKH.setDefaultCapable(false);
        btn_XoaLoaiKH.setFocusPainted(false);
        btn_XoaLoaiKH.setFocusable(false);
        btn_XoaLoaiKH.setIconTextGap(0);
        btn_XoaLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLoaiKHActionPerformed(evt);
            }
        });
        pnl3.add(btn_XoaLoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 110, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        pnl3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 300, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        pnl3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 300, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        pnl3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 300, 10));

        add(pnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 1, 510, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        GanThongTin();
        if (BLL.BLL_KH.KT_Sua(KH)) {
            DAO.DAO_KhachHang.Sua(KH);
            BLL.BLL_KH.dodulieu(tbl_KH);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed
    public static DTO.DTO_KH KH = new DTO_KH();
    public static DTO.DTO_LoaiKH Loai = new DTO.DTO_LoaiKH();
    
    private void GanThongTin() {
        KH.setMaKH(txt_MaKH.getText());
        GUI.mycombobox mb = (GUI.mycombobox) cbb_LoaiKH.getSelectedItem();
        KH.setMaLoaiKH(mb.value.toString());
        //System.out.println(KH.getMaLoaiKH());
        KH.setTenKH(txt_TenKH.getText());
        KH.setTuoi(txt_Tuoi.getText());
        if (rab_Nam.isSelected()) {
            KH.setGioiTinh(true);
        } else {
            KH.setGioiTinh(false);
        }
        //System.out.println(KH.isGioiTinh());
        KH.setSDT(txt_SDT.getText());
        KH.setCMND(txt_CMND.getText());
    }
    public static int vitri;
    public static String MaKH;
    private void tbl_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseClicked
        if (tbl_KH.getSelectedRowCount() == 1) {
            vitri = tbl_KH.getSelectedRow();
            MaKH = tbl_KH.getValueAt(vitri, 0).toString();
            ThongTinChiTiet(MaKH);
            ResultSet rs = DAO.DAO_KhachHang.LayKHMa(MaKH);
            btn_Chon.setEnabled(true);
            btn_Xoa.setEnabled(true);
            btn_CapNhat.setEnabled(true);
        }

    }//GEN-LAST:event_tbl_KHMouseClicked

    private void btn_ChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonActionPerformed
        frm_ThuePhong frm = frm_ThuePhong.form;
        frm.setVisible(true);
        frm.loadData_KH();
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) frm.cbb_KhachHang.getModel();
        for (int i = 0; i < frm.cbb_KhachHang.getItemCount(); i++) {
            mycombobox mb = (mycombobox) cbbModel.getElementAt(i);
            if (MaKH.equals(mb.value)) {
                frm.cbb_KhachHang.setSelectedIndex(i);
            } else {
            }
        }
    }//GEN-LAST:event_btn_ChonActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_KH.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaKH = tbl_KH.getValueAt(cacdong[i], 0).toString();
                if (BLL.BLL_KH.KT_Xoa(MaKH)) {
                    DAO.DAO_KhachHang.Xoa(MaKH);
                    thongbao.thongbao("Xóa Thành Công");
                }
            }
            BLL.BLL_KH.dodulieu(tbl_KH);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void txt_TuoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TuoiKeyReleased
        try {
            int sl = Integer.parseInt(txt_Tuoi.getText());
        } catch (Exception e) {
            txt_Tuoi.setText("01");
        }
    }//GEN-LAST:event_txt_TuoiKeyReleased

    private void btn_TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TruActionPerformed
        if (!txt_Tuoi.getText().equals("1")) {
            Tuoi(-1);
        }
    }//GEN-LAST:event_btn_TruActionPerformed

    private void btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CongActionPerformed
        Tuoi(1);
    }//GEN-LAST:event_btn_CongActionPerformed

    private void btn_ThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLoaiActionPerformed
//        frm_QuanLyChinh frm = frm_QuanLyChinh.b;
//        try {
//            frm.tab.setSelectedComponent(pnl_CungCapDichVu.form);
//        } catch (Exception e) {
//            pnl_CungCapDichVu pnl = new pnl_CungCapDichVu();
//            frm.tab.add("Cung cấp dịch vụ", pnl);
//            frm.tab.setSelectedComponent(pnl);
//        }
        pnl3.setVisible(true);
        BLL.BLL_LoaiKH.DoDuLieuBang(tbl_LoaiKH);
    }//GEN-LAST:event_btn_ThemLoaiActionPerformed
    private void GanDuLieuLoai() {
        Loai.setMaLoaiKH(txt_MaLoai.getText());
        Loai.setTenLoaiKH(txt_TenLoaiKH.getText());
        Loai.setTienGiam(Double.parseDouble(txt_TiemGiam.getText()));
        Loai.setMoTa(txt_MoTa.getText());
    }
    
    private void DienDuLieuVaoField(String MaLoai) {
        ResultSet rs = DAO.DAO_LoaiKH.LayTHeoMa(MaLoai);
        try {
            if (rs.next()) {
                txt_MaLoai.setText(rs.getString("MaLoaiKH"));
                txt_TenLoaiKH.setText(rs.getString("TenLoaiKH"));
                txt_TiemGiam.setText(rs.getString("TienGiam"));
                txt_MoTa.setText(rs.getString("MoTa"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnl_KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tbl_LoaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiKHMouseClicked
        if (tbl_LoaiKH.getSelectedRowCount() == 1) {
            btn_CapnhatLoai.setEnabled(true);
            btn_XoaLoaiKH.setEnabled(true);
            int vitri = tbl_LoaiKH.getSelectedRow();
            String MaLoaiKH = tbl_LoaiKH.getValueAt(vitri, 0).toString();
            DienDuLieuVaoField(MaLoaiKH);
            txt_MaLoai.setFocusable(false);
        }
    }//GEN-LAST:event_tbl_LoaiKHMouseClicked

    private void btn_SuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLoaiActionPerformed
        GanDuLieuLoai();
        if (BLL.BLL_LoaiKH.KT_Sua(Loai)) {
            DAO.DAO_LoaiKH.Sua(Loai);
            BLL.BLL_LoaiKH.DoDuLieuBang(tbl_LoaiKH);
            LamMoiLoai();
            // LamMoi();
        }
        

    }//GEN-LAST:event_btn_SuaLoaiActionPerformed

    private void txt_TiemGiamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TiemGiamKeyReleased
        try {
            int sl = Integer.parseInt(txt_TiemGiam.getText());
            
        } catch (Exception e) {
            txt_TiemGiam.setText("0");
            
        }
    }//GEN-LAST:event_txt_TiemGiamKeyReleased

    private void txt_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKeyReleased
        String tukhoa = txt_TimKiem.getText();
        BLL.BLL_KH.TimKiem(tbl_KH, tukhoa);
    }//GEN-LAST:event_txt_TimKiemKeyReleased

    private void txt_TiemGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TiemGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TiemGiamActionPerformed

    private void btn_ThemKHbtn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKHbtn_ThemActionPerformed
        // TODO add your handling code here:
        KH.setMaKH(txt_MaKH.getText());
//        GUI.mycombobox mb = (GUI.mycombobox) cbb_LoaiKH.getSelectedItem();
//        KH.setMaLoaiKH(Integer.parseInt(mb.value.toString()));
//        //System.out.println(KH.getMaLoaiKH());
//        KH.setTenKH(txt_TenKH.getText());
//        KH.setTuoi(txt_Tuoi.getText());
//        if (rab_Nam.isSelected()) {
//            KH.setGioiTinh(true);
//        } else {
//            KH.setGioiTinh(false);
//        }
//        //System.out.println(KH.isGioiTinh());
//        KH.setSDT(txt_SDT.getText());
//        KH.setCMND(txt_CMND.getText());
        GanThongTin();
        boolean kt = BLL.BLL_KH.KT_Them(KH);
        if (kt) {
            DAO.DAO_KhachHang.Them(KH);
            BLL.BLL_KH.dodulieu(tbl_KH);
        }
    }//GEN-LAST:event_btn_ThemKHbtn_ThemActionPerformed

    private void btn_XoaLoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLoaiKHActionPerformed
        // TODO add your handling code here:
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_LoaiKH.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaLoaiKH = tbl_LoaiKH.getValueAt(cacdong[i], 0).toString();
                if (BLL.BLL_LoaiKH.KT_Xoa(MaLoaiKH)) {
                    DAO.DAO_LoaiKH.Xoa(MaLoaiKH);
                    BLL.BLL_LoaiKH.DoDuLieuBang(tbl_LoaiKH);
                    //  LamMoi();
                    LamMoiLoai();
                    thongbao.thongbao("Xóa Thành Công");
                }
            }
        }
    }//GEN-LAST:event_btn_XoaLoaiKHActionPerformed

    private void btn_ThemLoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLoaiKHActionPerformed
        // TODO add your handling code here:
        GanDuLieuLoai();
        if (BLL.BLL_LoaiKH.KT_Them(Loai)) {
            DAO.DAO_LoaiKH.Them(Loai);
            BLL.BLL_LoaiKH.DoDuLieuBang(tbl_LoaiKH);
            // LamMoi();
        }
    }//GEN-LAST:event_btn_ThemLoaiKHActionPerformed

    private void btn_MoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiKHActionPerformed
        // TODO add your handling code here:
        lammoikh();
    }//GEN-LAST:event_btn_MoiKHActionPerformed
    private void LamMoiLoai() {
        txt_TenLoaiKH.setText("");
        txt_MaLoai.setText("");
        txt_TiemGiam.setText("");
        txt_MoTa.setText("");
        txt_MaLoai.setFocusable(true);
        
    }
    private void lammoikh(){
        txt_MaKH.setText("KH");
        txt_TenKH.setText("");
        txt_Tuoi.setText("0");
        buttonGroup1.clearSelection();
        txt_SDT.setText("");
        txt_CMND.setText("");
        cbb_LoaiKH.setSelectedIndex(0);
    }
    
    private void ThongTinChiTiet(String MaKH) {
        ResultSet rs = DAO.DAO_KhachHang.LayKHMa(MaKH);
        try {
            if (rs.next()) {
                txt_MaKH.setText(rs.getString("MaKhachHang"));
                String MaLoai = rs.getString("MaloaiKH");
                DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb_LoaiKH.getModel();
                for (int i = 0; i < cbb_LoaiKH.getItemCount(); i++) {
                    mycombobox mb = (mycombobox) cbbModel.getElementAt(i);
                    if (MaLoai.equals(mb.value)) {
                        cbb_LoaiKH.setSelectedIndex(i);
                    } else {
                    }
                }
                txt_TenKH.setText(rs.getString("TenKhachHang"));
                txt_Tuoi.setText(String.valueOf(rs.getInt("Tuoi")));
                if (rs.getBoolean("GioiTinh") == true) {
                    rab_Nam.setSelected(true);
                } else {
                    rab_Nu.setSelected(true);
                }
                txt_SDT.setText(rs.getString("SoDienThoai"));
                txt_CMND.setText(rs.getString("SoCMND"));
            }
        } catch (SQLException ex) {
            
        }
    }
    
    public void moform() {
        btn_Chon.setVisible(true);
        loadData_LoaiKH();
    }
    
    private void Tuoi(int giatri) {
        int sl = Integer.parseInt(txt_Tuoi.getText());
        sl = sl + (giatri);
        txt_Tuoi.setText(String.valueOf(sl));
    }
    
    private void LamMoi() {
        FrmMain frm = FrmMain.b;
        frm.tab.remove(form);
        pnl_KhachHang pnl = new pnl_KhachHang();
        frm.tab.add("Khách hàng", pnl);
        frm.tab.setSelectedComponent(pnl);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_CapnhatLoai;
    private javax.swing.JButton btn_Chon;
    private javax.swing.JButton btn_Cong;
    private javax.swing.JButton btn_MoiKH;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.JButton btn_ThemLoai;
    private javax.swing.JButton btn_ThemLoaiKH;
    private javax.swing.JButton btn_Tru;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaLoaiKH;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbb_LoaiKH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_CMND;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_LoaiKH;
    private javax.swing.JLabel lbl_LoaiKH2;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaLoai;
    private javax.swing.JLabel lbl_MoTa;
    private javax.swing.JLabel lbl_PhanTram;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_TenLoai;
    private javax.swing.JLabel lbl_TienGiam;
    private javax.swing.JLabel lbl_TimKiem;
    private javax.swing.JLabel lbl_Tuoi;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JRadioButton rab_Nam;
    private javax.swing.JRadioButton rab_Nu;
    private javax.swing.JTable tbl_KH;
    public javax.swing.JTable tbl_LoaiKH;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaLoai;
    private javax.swing.JTextArea txt_MoTa;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenLoaiKH;
    private javax.swing.JTextField txt_TiemGiam;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_Tuoi;
    // End of variables declaration//GEN-END:variables
}
