/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_DichVu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class pnl_CungCapDichVu extends javax.swing.JPanel {

    DTO.DTO_DichVu dv = new DTO_DichVu();
    /**
     * Creates new form pnl_CungCapDichVu
     */
    public static pnl_CungCapDichVu form;
//public static void MaNgauNhien(){
//Random rd=new Random();
//int number = rd.nextInt(); 
//    System.out.println(""+number);
//int number1 = rd.nextInt(999);
//    System.out.println(""+number1);
//}

    public pnl_CungCapDichVu() {
        initComponents();
        form = this;
        BLL.BLL_CungCapDichVu.DoDuLieuBangDichVu(tbl_CungCapDV);
        BLL.BLL_CungCapDichVu.Load_cbbDonVi(cbb_DonVi);
        btn_Capnhat.setEnabled(false);
        btn_xoa.setEnabled(false);
//        MaNgauNhien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lbl_MaDV = new javax.swing.JLabel();
        lbl_TenDV = new javax.swing.JLabel();
        lbl_DonVi = new javax.swing.JLabel();
        lbl_DonGia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        lbl_GhiChu = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        txt_TenDV = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        cbb_DonVi = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_Capnhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_CungCapDV = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1380, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl.setBackground(new java.awt.Color(153, 153, 255));
        pnl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaDV.setText("Mã dịch vụ ");
        pnl.add(lbl_MaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lbl_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenDV.setText("Tên dịch vụ");
        pnl.add(lbl_TenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_DonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonVi.setText("Đơn vị");
        pnl.add(lbl_DonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lbl_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonGia.setText("Đơn giá");
        pnl.add(lbl_DonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane1.setViewportView(txt_GhiChu);

        pnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 504, -1));

        lbl_GhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GhiChu.setText("Ghi chú");
        pnl.add(lbl_GhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txt_MaDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaDV.setText("DV");
        txt_MaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaDVActionPerformed(evt);
            }
        });
        pnl.add(txt_MaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, 40));

        txt_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl.add(txt_TenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 300, 40));

        txt_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DonGia.setText("0");
        txt_DonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DonGiaKeyReleased(evt);
            }
        });
        pnl.add(txt_DonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 300, 40));

        cbb_DonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnl.add(cbb_DonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 300, 40));

        btn_Them.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnthem.png"))); // NOI18N
        btn_Them.setBorder(null);
        btn_Them.setBorderPainted(false);
        btn_Them.setContentAreaFilled(false);
        btn_Them.setDefaultCapable(false);
        btn_Them.setFocusPainted(false);
        btn_Them.setFocusable(false);
        btn_Them.setIconTextGap(0);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        pnl.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 40));

        btn_Capnhat.setBackground(new java.awt.Color(255, 255, 255));
        btn_Capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btncapnhat.png"))); // NOI18N
        btn_Capnhat.setBorder(null);
        btn_Capnhat.setBorderPainted(false);
        btn_Capnhat.setContentAreaFilled(false);
        btn_Capnhat.setDefaultCapable(false);
        btn_Capnhat.setFocusPainted(false);
        btn_Capnhat.setFocusable(false);
        btn_Capnhat.setIconTextGap(0);
        btn_Capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        pnl.add(btn_Capnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 110, 40));

        btn_xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnxoa.png"))); // NOI18N
        btn_xoa.setBorder(null);
        btn_xoa.setBorderPainted(false);
        btn_xoa.setContentAreaFilled(false);
        btn_xoa.setDefaultCapable(false);
        btn_xoa.setFocusPainted(false);
        btn_xoa.setFocusable(false);
        btn_xoa.setIconTextGap(0);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        pnl.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 110, 40));

        btn_moi.setBackground(new java.awt.Color(255, 255, 255));
        btn_moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnmoi.png"))); // NOI18N
        btn_moi.setBorder(null);
        btn_moi.setBorderPainted(false);
        btn_moi.setContentAreaFilled(false);
        btn_moi.setDefaultCapable(false);
        btn_moi.setFocusPainted(false);
        btn_moi.setFocusable(false);
        btn_moi.setIconTextGap(0);
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        pnl.add(btn_moi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 110, 40));

        add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 610));

        tbl_CungCapDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị", "Đơn giá"
            }
        ));
        tbl_CungCapDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CungCapDVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_CungCapDV);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 860, 580));
    }// </editor-fold>//GEN-END:initComponents
private void GanDuLieu() {
        dv.setMaDV(txt_MaDV.getText());
        dv.setTenDV(txt_TenDV.getText());
        dv.setDonVi(cbb_DonVi.getSelectedItem().toString());
        dv.setDonGia(txt_DonGia.getText());
        dv.setGhiChu(txt_GhiChu.getText());
    }

    private void GanDuLieuVaoTextField(String MaDV) {
        ResultSet rs = DAO.DAO_CungCapDichVu.LayDVTheoMa(MaDV);
        try {
            if (rs.next()) {
                txt_MaDV.setText(rs.getString("MaDichVu"));
                txt_TenDV.setText(rs.getString("TenDichVu"));
                for (int i = 0; i < cbb_DonVi.getItemCount(); i++) {
                    if (rs.getString("DonVi").matches(cbb_DonVi.getItemAt(i))) {
                        cbb_DonVi.setSelectedIndex(i);
                    } else {
                    }
                }
                txt_DonGia.setText(ChuyenDoi.DinhDangSo(rs.getDouble("DonGia")));
                txt_GhiChu.setText(rs.getString("GhiChu"));
            }
        } catch (SQLException ex) {

        }
    }
    private void txt_MaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaDVActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        GanDuLieu();
        if (BLL.BLL_CungCapDichVu.KT_Them(dv)) {
            DAO.DAO_CungCapDichVu.Them(dv);
            BLL.BLL_CungCapDichVu.DoDuLieuBangDichVu(tbl_CungCapDV);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_CungCapDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CungCapDVMouseClicked
        if (tbl_CungCapDV.getSelectedRowCount() == 1) {
            btn_Capnhat.setEnabled(true);
            btn_xoa.setEnabled(true);
            txt_MaDV.setFocusable(false);
            int vitri = tbl_CungCapDV.getSelectedRow();
            String MaDV = tbl_CungCapDV.getValueAt(vitri, 0).toString();
            GanDuLieuVaoTextField(MaDV);
        }
    }//GEN-LAST:event_tbl_CungCapDVMouseClicked

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_CungCapDV.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaDV = tbl_CungCapDV.getValueAt(cacdong[i], 0).toString();
                if (BLL.BLL_CungCapDichVu.KT_Xoa(MaDV)) {
                    DAO.DAO_CungCapDichVu.Xoa(MaDV);
                }

            }
            BLL.BLL_CungCapDichVu.DoDuLieuBangDichVu(tbl_CungCapDV);
            LamMoi();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        GanDuLieu();
        if (BLL.BLL_CungCapDichVu.KT_Sua(dv)) {
            DAO.DAO_CungCapDichVu.Sua(dv);
            BLL.BLL_CungCapDichVu.DoDuLieuBangDichVu(tbl_CungCapDV);
            LamMoi();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void txt_DonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DonGiaKeyReleased
        try {
            double so = ChuyenDoi.ChuyenSangSo(txt_DonGia.getText());
            String sotien = ChuyenDoi.DinhDangSo(so);
            txt_DonGia.setText(sotien);
        } catch (Exception e) {
            txt_DonGia.setText("0");
        }

    }//GEN-LAST:event_txt_DonGiaKeyReleased
    private void LamMoi() {
        txt_MaDV.setText("");
        txt_TenDV.setText("");
        txt_DonGia.setText("");
        txt_GhiChu.setText("");
        btn_Capnhat.setEnabled(false);
        btn_xoa.setEnabled(false);
        txt_MaDV.setFocusable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Capnhat;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_DonVi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_DonGia;
    private javax.swing.JLabel lbl_DonVi;
    private javax.swing.JLabel lbl_GhiChu;
    private javax.swing.JLabel lbl_MaDV;
    private javax.swing.JLabel lbl_TenDV;
    private javax.swing.JPanel pnl;
    private javax.swing.JTable tbl_CungCapDV;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_TenDV;
    // End of variables declaration//GEN-END:variables
}
