/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_ThongKe;
import DAO.ThongKeHD_service;
import DAO.ThongKeHD_serviceImpl;
import DTO.DTO_HoaDon;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Dimension;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;

import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

;

/**
 *
 * @author ADMIN
 */
public class pnl_ThongKe extends javax.swing.JPanel {

    private ThongKeHD_service thongkeservice = null;
    /**
     * Creates new form pnl_ThongKe
     */
    public static pnl_ThongKe form;

    public pnl_ThongKe() {
        initComponents();
        form = this;
        // BLL.BLL_ThongKe.DoBangTatCa(tbl_HoaDon);
        ResultSet rs = DAO.DAO_ThongKe.LayTatCaLuong();
        BLL.BLL_ThongKe.DoBangLuong(tbl_Luong, rs);
        DoField();
        this.thongkeservice = new ThongKeHD_serviceImpl();
        setDataToChart1();//xung dot vs du lieu
    }

    private void DoField() {

        /* ResultSet rs = DAO.DAO_ThongKe.LayTatCa2();
        try {
        if (rs.next()) {
        lbl_DV.setText(ChuyenDoi.DinhDangSo(rs.getDouble("dichvu")));
        lbl_TienPhong.setText(ChuyenDoi.DinhDangSo(rs.getDouble("tienphong")));
        lbl_Tong.setText(ChuyenDoi.DinhDangSo(rs.getDouble("doanhthu")));
        lbl_SoHD.setText(rs.getString("SoHD"));
        }
        } catch (SQLException ex) {
        
        }*/
        //Lương
        ResultSet rsLuong = DAO.DAO_ThongKe.LayTatCaLuong2();
        try {
            if (rsLuong.next()) {
                lbl_TongLuong.setText(ChuyenDoi.DinhDangSo(rsLuong.getDouble("tongnhan")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnl_ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setDataToChart1() {
        List<DTO.DTO_HoaDon> listItem = thongkeservice.getlistbyhoadon();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listItem != null) {
            for (DTO_HoaDon item : listItem) {
                dataset.addValue((Number) item.getThanhTien(), "Mã Hóa Đơn", item.getMaDP());
            }
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu Đồ Thống Kê Hóa Đơn".toUpperCase(),
                "Mã Hóa Đơn", "Thành Tiền",
                dataset, PlotOrientation.VERTICAL, false, true, false);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(pnl_bieudoTK.getWidth(), 500));

        pnl_bieudoTK.removeAll();
        pnl_bieudoTK.setLayout(new CardLayout());
        pnl_bieudoTK.add(chartPanel);
        pnl_bieudoTK.validate();
        pnl_bieudoTK.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bieudoTK = new javax.swing.JPanel();
        pnl4 = new javax.swing.JPanel();
        pnl5 = new javax.swing.JPanel();
        lbl_ThongKeLuong = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Luong = new javax.swing.JTable();
        pnl6 = new javax.swing.JPanel();
        lbl_TongLuong2 = new javax.swing.JLabel();
        lbl_TongLuong = new javax.swing.JLabel();
        btn_InPDF = new javax.swing.JButton();
        btn_Inexcel = new javax.swing.JButton();
        date_ngay3 = new com.toedter.calendar.JDateChooser();
        date_ngay4 = new com.toedter.calendar.JDateChooser();
        lbl_Den2 = new javax.swing.JLabel();
        btn_Xem2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1380, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnl_bieudoTKLayout = new javax.swing.GroupLayout(pnl_bieudoTK);
        pnl_bieudoTK.setLayout(pnl_bieudoTKLayout);
        pnl_bieudoTKLayout.setHorizontalGroup(
            pnl_bieudoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pnl_bieudoTKLayout.setVerticalGroup(
            pnl_bieudoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        add(pnl_bieudoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, 560));

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl5.setBackground(new java.awt.Color(255, 255, 255));

        lbl_ThongKeLuong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_ThongKeLuong.setText("THỐNG KÊ LƯƠNG NHÂN VIÊN");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(lbl_ThongKeLuong)
                .addGap(120, 120, 120))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ThongKeLuong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl4.add(pnl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 630, 40));

        tbl_Luong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên", "Số ngày nghỉ", "Số ngày làm", "Ngày nhận", "Tổng nhận"
            }
        ));
        jScrollPane2.setViewportView(tbl_Luong);

        pnl4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 630, 420));

        pnl6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TongLuong2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_TongLuong2.setText("Tổng lương:");

        lbl_TongLuong.setBackground(new java.awt.Color(0, 153, 153));
        lbl_TongLuong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_TongLuong.setOpaque(true);

        btn_InPDF.setBackground(new java.awt.Color(255, 255, 255));
        btn_InPDF.setForeground(new java.awt.Color(255, 255, 255));
        btn_InPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnpdf.png"))); // NOI18N
        btn_InPDF.setBorder(null);
        btn_InPDF.setBorderPainted(false);
        btn_InPDF.setContentAreaFilled(false);
        btn_InPDF.setDefaultCapable(false);
        btn_InPDF.setFocusPainted(false);
        btn_InPDF.setFocusable(false);
        btn_InPDF.setIconTextGap(0);
        btn_InPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InPDFActionPerformed(evt);
            }
        });

        btn_Inexcel.setBackground(new java.awt.Color(255, 255, 255));
        btn_Inexcel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Inexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnexcel.png"))); // NOI18N
        btn_Inexcel.setBorder(null);
        btn_Inexcel.setBorderPainted(false);
        btn_Inexcel.setContentAreaFilled(false);
        btn_Inexcel.setDefaultCapable(false);
        btn_Inexcel.setFocusPainted(false);
        btn_Inexcel.setFocusable(false);
        btn_Inexcel.setIconTextGap(0);
        btn_Inexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TongLuong2)
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addComponent(lbl_TongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_InPDF)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Inexcel)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TongLuong2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_InPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pnl4.add(pnl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 640, 140));
        pnl4.add(date_ngay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 150, 40));
        pnl4.add(date_ngay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 40));

        lbl_Den2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbl_Den2.setText("đến");
        pnl4.add(lbl_Den2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 20));

        btn_Xem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Xem2.setText("Xem");
        btn_Xem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xem2ActionPerformed(evt);
            }
        });
        pnl4.add(btn_Xem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, 40));

        add(pnl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 640, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Xem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xem2ActionPerformed
        SimpleDateFormat C = new SimpleDateFormat("dd/MM/yyyy");
        Date date1 = date_ngay4.getDate();
        Date date2 = date_ngay3.getDate();
        try {
            ResultSet rs = DAO.DAO_ThongKe.LayLuongTheoTG(C.format(date1), C.format(date2));
            BLL.BLL_ThongKe.DoBangLuong(tbl_Luong, rs);
        } catch (Exception e) {
            thongbao.loi("Chọn ngày");
            return;
        }
        ResultSet rs1 = DAO.DAO_ThongKe.LayTheoKhoangTG2(C.format(date1), C.format(date2));
        try {
            if (rs1.next()) {
                lbl_TongLuong.setText(ChuyenDoi.DinhDangSo(rs1.getDouble("tongnhan")));
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_btn_Xem2ActionPerformed

    private void btn_InPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InPDFActionPerformed
        // TODO add your handling code here:
        // XSSFWorkbook wb = new XSSFWorkbook();
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "Thongkeluong.pdf"));

            doc.open();
            PdfPTable tbl = new PdfPTable(5);
            tbl.addCell("Tên Nhân Viên");
            tbl.addCell("Số Ngày Nghỉ");
            tbl.addCell("Số Ngày Làm");
            tbl.addCell("Ngày Nhận");
            tbl.addCell("Tổng Nhận");

            for (int i = 0; i < tbl_Luong.getRowCount(); i++) {

                String tennv = tbl_Luong.getValueAt(i, 0).toString();
                String snn = tbl_Luong.getValueAt(i, 1).toString();
                String snl = tbl_Luong.getValueAt(i, 2).toString();
                String nn = tbl_Luong.getValueAt(i, 3).toString();
                String tn = tbl_Luong.getValueAt(i, 4).toString();

                tbl.addCell(tennv);
                tbl.addCell(snn);
                tbl.addCell(snl);
                tbl.addCell(nn);
                tbl.addCell(tn);
            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null, "Đang tải PDF", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(pnl_ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(pnl_ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();

    }//GEN-LAST:event_btn_InPDFActionPerformed
    private static XSSFCellStyle createStyleForTitle(XSSFWorkbook workbook) {
        XSSFFont font = workbook.createFont();
        font.setBold(true);
        XSSFCellStyle style = workbook.createCellStyle();
        style.setFont(font);
        font.setColor(IndexedColors.RED.getIndex());
        font.setBold(true);

        return style;
    }
    private void btn_InexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InexcelActionPerformed
        // TODO add your handling code here:
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("Thống Kê Lương");
            XSSFCellStyle style = createStyleForTitle(workbook);

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Danh Sách Lương");
            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Tên Nhân Viên");
            cell.setCellStyle(style);

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Số Ngày Nghỉ");
            cell.setCellStyle(style);

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Số Ngày Làm");
            cell.setCellStyle(style);
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Ngày Nhận");
            cell.setCellStyle(style);
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Tổng Nhận");
            cell.setCellStyle(style);

            for (int i = 0; i < tbl_Luong.getRowCount(); i++) {
                row = spreadsheet.createRow((short) 4 + i);

                row.setHeight((short) 400);

                row.createCell(0).setCellValue(tbl_Luong.getValueAt(i, 0).toString());
                row.createCell(1).setCellValue(tbl_Luong.getValueAt(i, 1).toString());
                row.createCell(2).setCellValue(tbl_Luong.getValueAt(i, 2).toString());
                row.createCell(3).setCellValue(tbl_Luong.getValueAt(i, 3).toString());
                row.createCell(4).setCellValue(tbl_Luong.getValueAt(i, 4).toString());

            }
            FileOutputStream out = new FileOutputStream(path + "Thongkeluongexcel.xlsx");
            workbook.write(out);

            out.close();
            JOptionPane.showMessageDialog(null, "Đang tải File Excel", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_InexcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InPDF;
    private javax.swing.JButton btn_Inexcel;
    private javax.swing.JButton btn_Xem2;
    private com.toedter.calendar.JDateChooser date_ngay3;
    private com.toedter.calendar.JDateChooser date_ngay4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Den2;
    private javax.swing.JLabel lbl_ThongKeLuong;
    private javax.swing.JLabel lbl_TongLuong;
    private javax.swing.JLabel lbl_TongLuong2;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl_bieudoTK;
    private javax.swing.JTable tbl_Luong;
    // End of variables declaration//GEN-END:variables
}
