/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_Phong;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class pnl_LoaiPhong extends javax.swing.JPanel {

    /**
     * Creates new form pnl_LoaiPhong
     */
    public static pnl_LoaiPhong form;

    public pnl_LoaiPhong() {
        initComponents();
        BLL.BLL_LoaiPhong.DoDuLieuBang(tbl_LoaiPhong);
        form = this;
        btn_Capnhat.setEnabled(false);
        btn_xoa.setEnabled(false);
    }

    public static DTO.DTO_Phong LP = new DTO_Phong();

    private void GanThongTin() {
        LP.setMaLoaiPhong(txt_MaLoaiPhong.getText());
        LP.setTenLoaiPhong(txt_TenLoaiPhong.getText());
        LP.setGiaTheoGio(txt_GiaGio.getText());
        LP.setGiaTheoNgay(txt_GiaNgay.getText());
    }
    private void moi(){
        txt_MaLoaiPhong.setText("");
        txt_TenLoaiPhong.setText("");
        txt_GiaGio.setText("0");
        txt_GiaNgay.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Them1 = new javax.swing.JButton();
        btn_Capnhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        lbl_MaLoaiPhong = new javax.swing.JLabel();
        lbl_TenLoaiPhong = new javax.swing.JLabel();
        lbl_GiaGio = new javax.swing.JLabel();
        lbl_GiaNgay = new javax.swing.JLabel();
        txt_MaLoaiPhong = new javax.swing.JTextField();
        txt_TenLoaiPhong = new javax.swing.JTextField();
        txt_GiaGio = new javax.swing.JTextField();
        txt_GiaNgay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_LoaiPhong = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Them1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnthem.png"))); // NOI18N
        btn_Them1.setBorder(null);
        btn_Them1.setBorderPainted(false);
        btn_Them1.setContentAreaFilled(false);
        btn_Them1.setDefaultCapable(false);
        btn_Them1.setFocusPainted(false);
        btn_Them1.setFocusable(false);
        btn_Them1.setIconTextGap(0);
        btn_Them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        add(btn_Them1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 110, 40));

        btn_Capnhat.setBackground(new java.awt.Color(255, 255, 255));
        btn_Capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btncapnhat.png"))); // NOI18N
        btn_Capnhat.setBorder(null);
        btn_Capnhat.setBorderPainted(false);
        btn_Capnhat.setContentAreaFilled(false);
        btn_Capnhat.setDefaultCapable(false);
        btn_Capnhat.setFocusPainted(false);
        btn_Capnhat.setFocusable(false);
        btn_Capnhat.setIconTextGap(0);
        btn_Capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        add(btn_Capnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 110, 40));

        btn_xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/btnxoa.png"))); // NOI18N
        btn_xoa.setBorder(null);
        btn_xoa.setBorderPainted(false);
        btn_xoa.setContentAreaFilled(false);
        btn_xoa.setDefaultCapable(false);
        btn_xoa.setFocusPainted(false);
        btn_xoa.setFocusable(false);
        btn_xoa.setIconTextGap(0);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 110, 40));

        lbl_MaLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaLoaiPhong.setText("Mã loại phòng");
        add(lbl_MaLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lbl_TenLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenLoaiPhong.setText("Tên loại phòng");
        add(lbl_TenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lbl_GiaGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GiaGio.setText("Giá theo giờ");
        add(lbl_GiaGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        lbl_GiaNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GiaNgay.setText("Giá ngày");
        add(lbl_GiaNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        txt_MaLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txt_MaLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, 30));

        txt_TenLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txt_TenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 210, 30));

        txt_GiaGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_GiaGio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_GiaGioKeyReleased(evt);
            }
        });
        add(txt_GiaGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 230, 30));

        txt_GiaNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_GiaNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_GiaNgayKeyReleased(evt);
            }
        });
        add(txt_GiaNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 230, 30));

        tbl_LoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_LoaiPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại phòng", "Tên loại phòng", "Giá theo giờ", "Giá theo ngày"
            }
        ));
        tbl_LoaiPhong.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_LoaiPhong.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbl_LoaiPhong.setRowHeight(20);
        tbl_LoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_LoaiPhong);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 860, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        GanThongTin();
        if (BLL.BLL_LoaiPhong.KT_Them(LP)) {
            DAO.DAO_LoaiPhong.Them(LP);
            BLL.BLL_LoaiPhong.DoDuLieuBang(tbl_LoaiPhong);
            moi();
        } else {
        }

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_LoaiPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiPhongMouseClicked
        if (tbl_LoaiPhong.getSelectedRowCount() == 1) {
            btn_Capnhat.setEnabled(true);
            btn_xoa.setEnabled(true);
        }
        int vitri = tbl_LoaiPhong.getSelectedRow();
        GanTTVaoTxt(vitri);
        txt_MaLoaiPhong.setFocusable(false);
    }//GEN-LAST:event_tbl_LoaiPhongMouseClicked

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "Bạn chắc chắn xóa?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_LoaiPhong.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaLoaiPhong = tbl_LoaiPhong.getValueAt(cacdong[i], 0).toString();
                if (BLL.BLL_LoaiPhong.KT_Xoa(MaLoaiPhong)) {
                    DAO.DAO_LoaiPhong.Xoa(MaLoaiPhong);
                     BLL.BLL_LoaiPhong.DoDuLieuBang(tbl_LoaiPhong);
                     moi();
                }

            }
           // LamMoi();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        if (tbl_LoaiPhong.getSelectedRowCount() != 1) {
            thongbao.ktlai("Chọn 1 dòng để sửa");
        } else {

            GanThongTin();
            if (BLL.BLL_LoaiPhong.KT_Sua(LP)) {
                DAO.DAO_LoaiPhong.Sua(LP);
                BLL.BLL_LoaiPhong.DoDuLieuBang(tbl_LoaiPhong);
                //LamMoi();
                moi();
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_GiaGioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiaGioKeyReleased
        try {
            double so = ChuyenDoi.ChuyenSangSo(txt_GiaGio.getText());
            String sotien = ChuyenDoi.DinhDangSo(so);
            txt_GiaGio.setText(sotien);
        } catch (Exception e) {
            txt_GiaGio.setText("0");
        }
    }//GEN-LAST:event_txt_GiaGioKeyReleased

    private void txt_GiaNgayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiaNgayKeyReleased
         try {
            double so = ChuyenDoi.ChuyenSangSo(txt_GiaNgay.getText());
            String sotien = ChuyenDoi.DinhDangSo(so);
            txt_GiaNgay.setText(sotien);
        } catch (Exception e) {
            txt_GiaNgay.setText("0");
        }
    }//GEN-LAST:event_txt_GiaNgayKeyReleased
    private void LamMoi() {
        FrmQLphongNew frm = FrmQLphongNew.form;
        pnl_LoaiPhong pnl = new pnl_LoaiPhong();
        frm.tab.remove(this);
        frm.tab.add("Loại phòng", pnl);
        frm.tab.setSelectedComponent(pnl);
    }

    private void GanTTVaoTxt(int vitri) {
        String MaLoaiPhong = tbl_LoaiPhong.getValueAt(vitri, 0).toString();
        ResultSet rs = DAO.DAO_LoaiPhong.LayLoaiTheoMa(MaLoaiPhong);
        try {
            if (rs.next()) {
                txt_MaLoaiPhong.setText(rs.getString("MaLoaiPhong"));
                txt_TenLoaiPhong.setText(rs.getString("TenLoaiPhong"));
                txt_GiaGio.setText(ChuyenDoi.DinhDangSo(rs.getDouble("GiaTheoGio")));
                txt_GiaNgay.setText(ChuyenDoi.DinhDangSo(rs.getDouble("GiaTheoNgay")));
            }
        } catch (SQLException ex) {

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Capnhat;
    private javax.swing.JButton btn_Them1;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_GiaGio;
    private javax.swing.JLabel lbl_GiaNgay;
    private javax.swing.JLabel lbl_MaLoaiPhong;
    private javax.swing.JLabel lbl_TenLoaiPhong;
    private javax.swing.JTable tbl_LoaiPhong;
    private javax.swing.JTextField txt_GiaGio;
    private javax.swing.JTextField txt_GiaNgay;
    private javax.swing.JTextField txt_MaLoaiPhong;
    private javax.swing.JTextField txt_TenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
